### ISSUE TITLE
Vue: Do the Vue stuff (Expanding the Vue ecosystem with foundational libraries support)

### ISSUE THREAD

**Issue by joshvanallen** [nxext/nx-extensions#1006]
As Vue is gaining popularity, it'll be best if we add some of foundation elements that most Vue applicaitons use. 
This is the initial libraries that should have generators.
- [ ] Nuxt
- [ ] Pinia
- [ ] Vuetify
- [ ] Vuebootstrap

**Comment by DominikPieper** [comment]
😂😂

but I believe, Nuxt isn’t ready yet. Just the Fundation

**Comment by DominikPieper** [comment]
I'll close this because of the deprecation of the Vue plugin in favor of the official @nx/vue plugin
