### ISSUE TITLE
Vue: Cannot create new workspace using preset due to missing @nx/js

### ISSUE THREAD

**Issue by sarahec** [nxext/nx-extensions#1016]
**Describe the bug**

Vue preset fails to install @nx/js before creating the app (which then fails)

**To Reproduce**

1. Run `npx create-nx-workspace` with `--preset=@nxext/vue` 
2. Give an app name when asked
3. Observe: ` >  NX   Cannot find module '@nx/js'` followed by a stack trace starting at `create-application-files.js`
4. You get a workspace without the app

**Expected behavior**

A new workspace containing the named app.

**Additional context**

This happens whether or not nx is installed globally

**Comment by DominikPieper** [comment]
I'll close this because of the deprecation of the Vue plugin in favor of the official @nx/vue plugin
