### ISSUE TITLE
Unable to build/serve Stencil library

### ISSUE THREAD

**Issue by dannymcgee** [nxext/nx-extensions#102]
### Repro:
1. Create a new Nx workspace
2. Install `@nxext/stencil`
3. Run `nx g @nxext/stencil:lib my-lib`
4. Run `nx build my-lib` or `nx serve my-lib`

### Expected:
Stencil library should build out to the `dist` directory

### Actual:
```
TypeError: Cannot read property 'root' of undefined
    at MapSubscriber.project (<project-dir>\node_modules\@nxext\stencil\src\builders\utils\stencil-runtime.js:165:98)
    at MapSubscriber._next (<project-dir>\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (<project-dir>\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TapSubscriber._next (<project-dir>\node_modules\rxjs\internal\operators\tap.js:65:26)
    at TapSubscriber.Subscriber.next (<project-dir>\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TapSubscriber._next (<project-dir>\node_modules\rxjs\internal\operators\tap.js:65:26)
    at TapSubscriber.Subscriber.next (<project-dir>\node_modules\rxjs\internal\Subscriber.js:66:18)
    at <project-dir>\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24

Job Output failed to validate. Errors:
    Data path ".error" should be string.
```
### Notes:
Typically you would need to add the `--buildable` and/or `--publishable` flag to the generate command for an Nx library, but this extension doesn't support those flags.

I'm trying to migrate a UI library over from Angular to Stencil, so I followed the instructions here to add the Stencil extension and generate a Storybook config for it. Unfortunately, Storybook won't run because it can't resolve `dist/libs/my-lib/loader`. Figured I just needed to build the library first, but no dice. Then I figured something about my current Nx workspace configuration might be borked or incompatible with this extension in some way, so I generated a new workspace with the "empty" preset, but was able to reproduce the same issue by following the steps above.

Let me know if you need any more information. I might fork this repo tonight to see if I can figure out what's going on and submit a PR.

**Comment by dannymcgee** [comment]
Small update on the progress I made (or didn't) tonight:
- Fixed the Job Output validation (need to return `{ success: false, error: err.message }`)
- Fixed the `'root' of undefined` issue (need some nullish coalescing in the `devServerConfig` definition in `stencil-runtime.ts`)

Unfortunately now the Stencil compiler is throwing errors (`cannot read property 'extendedDiagnostics' of undefined`). The e2e tests are all passing with flying colors though, and have been from the beginning, which is *maddening*. I can see the output files and everything, they look great.

The only difference I can spot between the e2e build and the playground build is that when I console log the Stencil config, the e2e build is printing properly resolved absolute paths for all of the output targets, while the playground build is not transforming the `dist` target paths for some reason. I haven't really started digging into that yet, but I suspect it's the culprit. I'm on Windows, and I had to fix a handful of other places where the paths were messed up due to a missed `normalize` call.

**Comment by DominikPieper** [comment]
Hey @dannymcgee 
The --buildable behavior will change in the future, the main branch already needs a --buildable for the serve yet. I'll take a deeper look as well and the path's problem ist a known problem for me, hard to fix as a not windows user. I started to add more e2e tests for that.
The library part needs some more stuff I'm already working on, but the bug strange. I'm able to reproduce it

**Comment by DominikPieper** [comment]
Okay, the serve part was a local change I had. I'll spin up my Windows VM, cause on Mac I'm able to run the serve. So hopefully again just a path error.

**Comment by DominikPieper** [comment]
I tried to reproduce, bus except the error I had cause of local changes I wasn't able to reproduce in the playground on windows. Are you able to push a repo which doesn't work on yours to github?

**Comment by dannymcgee** [comment]
@DominikPieper I'll give it another shot tonight after pulling your latest changes and see if I'm still having the issue

**Comment by dannymcgee** [comment]
@DominikPieper Went ahead and tested this out on my lunch break — the error output has gone away, but I'm getting the same actual result, which is that the only file generated is `dist/libs/ui/package.json`, which looks like this:

```json
{
  "name": "ui",
  "main": "./dist/index.cjs.js",
  "module": "./dist/index.js",
  "es2015": "./dist/esm/index.mjs",
  "es2017": "./dist/esm/index.mjs",
  "types": "./dist/types/index.d.ts",
  "collection": "./dist/collection/collection-manifest.json",
  "collection:main": "./dist/collection/index.js",
  "unpkg": "./dist/ui/ui.js",
  "files": [
    "dist/",
    "loader/"
  ]
}
```

**Comment by dannymcgee** [comment]
@DominikPieper One more quick note: After enabling error reporting I'm running into several `cannot read property ____ of null/undefined` errors. Making a targeted update to the [Stencil `tsconfig.lib.json`](https://github.com/nxext/nx-extensions/blob/main/packages/stencil/tsconfig.lib.json) will make these issues easier to debug:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "../../dist/out-tsc",
    "declaration": true,
    "types": ["node"],
    "strictNullChecks": true
  },
  "exclude": ["**/*.spec.ts"],
  "include": ["**/*.ts"]
}
```
I use the `strictNullChecks` flag on all of my TypeScript projects and I've found it pretty handy for preventing issues like this, but it's also kind of onerous to keep up with so it's a bit of a trade-off. You may want to just enable it locally/temporarily to find the issues and then revert.

**Comment by DominikPieper** [comment]
Can you look into the workspace.json? are the paths for the config okay?

**Comment by dannymcgee** [comment]
@DominikPieper Sorry for the delayed response!

Yes, but the angular/workspace.json always uses forward slashes for paths, regardless of platform. I'm not sure how nx/@angular-devkit deals with that, maybe they run all paths through a normalizer before doing any file system operations?

**Comment by pqt** [comment]
I'm also running into this issue myself.

My setup however is a basic `nx` generated repo (empty, for open-source), and then I added a basic 1 function node library, and then added the generated stencil `lib` with basic CSS. I cannot run any of the commands `serve`, `build`, `test`, or `e2e`.

**Comment by iAbhinav** [comment]
has anybody solved it yet?

**Comment by DominikPieper** [comment]
@iAbhinav not really. I wasn't able to reproduce the error yet. Do you have an example repo I could look at? Maybe with node version and OS informations to reproduce?
