### ISSUE TITLE
Stencil: conflicting peer dependencies on `npm i @nxext/stencil`

### ISSUE THREAD

**Issue by dgonzalezr** [nxext/nx-extensions#1055]
**Describe the bug**

Installing @nxext/stencil in a brand new Nx workspace throws conflicting peer dependencies warnings.

![CleanShot 2023-11-22 at 13 53 04@2x](https://github.com/nxext/nx-extensions/assets/328492/4b484ed6-38a0-43ca-867f-66aa4c3ac768)

I know that dependencies are pinned in the `package.json` of `@nxext/stencil`, but I am not sure if it can be the root cause.

![CleanShot 2023-11-22 at 13 57 27@2x](https://github.com/nxext/nx-extensions/assets/328492/53016659-f6a3-4fad-b78a-ea0d32ff5ea3)

**To Reproduce**

1. Create a new Nx workspace.
2. Add `@nxext/stencil` package

**Expected behavior**

Expecting no warning or error regarding dependencies or peer dependencies.

**Comment by dgonzalezr** [comment]
This seems to be solved with the latest release: v17.2.0, thanks a lot @DominikPieper 🙌🏼 🎉 

![CleanShot 2024-01-10 at 13 52 57@2x](https://github.com/nxext/nx-extensions/assets/328492/5ad03fea-bdd9-41b6-a3a5-0b43df61120f)

**Comment by DominikPieper** [comment]
Great 😄 I’ll close this now 😁
