### ISSUE TITLE
Stencil: missing support for Nx latest version (v18)

### ISSUE THREAD

**Issue by dgonzalezr** [nxext/nx-extensions#1071]
**Describe the bug**
Adding `@nxext/stencil` into a newly created Nx workspace with the latest version (v18) leads to an unresolved dependency tree error.

**To Reproduce**
1. Create a new Nx workspace: `npx create-nx-workspace@latest package-based --preset=npm`
2. Install `@nxext/stencil` as dev dependency: `npm i -D @nxext/stencil`

**Expected behavior**
Adding the `@nxext/stencil` dependency should not fail or be unable to resolve the dependency tree.

**Additional context**

![CleanShot 2024-02-22 at 09 29 53@2x](https://github.com/nxext/nx-extensions/assets/328492/55759244-ad37-4edb-9c0a-9c01c6e1d6d5)

**Comment by DominikPieper** [comment]
I pushed a release
