### ISSUE TITLE
General: Update NX workspace to the recent version

### ISSUE THREAD

**Issue by pawel-twardziak** [nxext/nx-extensions#1108]
**Is your feature request related to a problem? Please describe.**
Not fully compatible with the recent NX version

**Describe the solution you'd like**
Migrate the NX workspace

**Describe alternatives you've considered**
No alts.

**Additional context**
No additional context needed.

**Comment by pawel-twardziak** [comment]
@DominikPieper I will take it once the required stuff is ready 😸

**Comment by edbzn** [comment]
Hey, I'm actually updating to the latest Nx version cause I need it in my PR #1107. However, it's just the local Nx version, it does not change how the published packages behave. So I'm not sure about what you mean exactly in your statement "Not fully compatible with the recent NX version". We just published a new version (v19.1.0), and plugins should be compatible with Nx v19.x including any minor and patch versions.

**Comment by pawel-twardziak** [comment]
@edbzn yes, I've updated it to NX 19.4 and the pacakges got published. By the incompatibility I mean the internall API we are involving in the plugins. Versions > 19.4 offers some new feature without breaking changes as semver says. So without bumping up the local version we cannot involve the new features.
So, if you are going to update our NX workspace, the only thing I would have to do within this task is nothing :)

**Comment by pawel-twardziak** [comment]
@DominikPieper I reckon we can close this issue as @edbzn did the upgrade within his PR
