### ISSUE TITLE
ionic-angular:  NX   Both project and target have to be specified

### ISSUE THREAD

**Issue by rbalet** [nxext/nx-extensions#1121]
**Describe the bug**
When running `nx run myApp android` I do get the following error
`NX   Both project and target have to be specified`

I did correctly configure it by following [this documentation](https://nxext.dev/docs/ionic-angular/generators.html) and I have the following code in my `project.json` file

```
    "run": {
      "executor": "@nxext/capacitor:cap",
      "options": {
        "cmd": "run"
      },
      "configurations": {
        "ios": {
          "cmd": "run ios"
        },
        "android": {
          "cmd": "run android"
        }
      }
    },
```

**To Reproduce**
1. Init an angular application `nx g @nx/angular:application [name] --directory=apps/[name]`
2. update the configuration `nx g @nxext/ionic-angular:configuration` -> select the newly created app
3. run `nx build [name]`
4. run `nx sync [name]`
5. run `nx run [name] android`
6. See the error in the CLI

Not: I tried to do that with the 

**Expected behavior**
Running and opening AndroidStudio

**Additional context**
```
    "@nx/angular": "19.8.4",
    "@nx/devkit": "19.8.4",
    "@nx/eslint": "19.8.4",
    "@nx/eslint-plugin": "19.8.4",
    "@nx/jest": "19.8.4",
    "@nx/js": "19.8.4",
    "@nx/playwright": "19.8.4",
    "@nx/web": "19.8.4",
    "@nx/workspace": "19.8.4",
    "@nxext/capacitor": "19.1.0",
    "@nxext/ionic-angular": "^19.1.0",
```

**Comment by edbzn** [comment]
Run is a native Nx command, so you must execute `nx run my-project:run:android`.

**Comment by rbalet** [comment]
@edbzn thx again :)
