### ISSUE TITLE
Stencil: semantic versioning mixed up 🤔 ?

### ISSUE THREAD

**Issue by dgonzalezr** [nxext/nx-extensions#1133]
**Describe the bug**
Did SemVer get a bit mixed up? A couple of weeks back, v19.1.0 came out, but then just days later, we saw v19.0.1 and v19.0.2 drop. Was this intentional?

![CleanShot 2024-10-12 at 18 39 16@2x](https://github.com/user-attachments/assets/57a6c2f1-d376-4408-a353-ba7b149672da)

Shouldn't we expect v19.1.1 and v19.1.2 instead?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by DominikPieper** [comment]
Sorry for the confusion. With the new auto release from the repository some releases where pushed until everything was set up completely 😅

**Comment by dgonzalezr** [comment]
Thank you @DominikPieper for your answer. Should we expect a new release that continues with the semantic versioning from v19.1.0?

**Comment by dgonzalezr** [comment]
I saw that v20.0.1 has been released. We can close this issue now 🙂
