### ISSUE TITLE
Solid: Support nx v20

### ISSUE THREAD

**Issue by sudokar** [nxext/nx-extensions#1134]
### **Is your feature request related to a problem? Please describe.**

I have set up a new repo using Nx v20 along with `@nxext/solid@19.0.2`. Upon running `nx g @nxext/solid:app my-app` getting the below error.

![image](https://github.com/user-attachments/assets/4049a437-8239-4cc9-9d4f-031a5a4cfdfe)

### **Describe the solution you'd like**

I think, support for nx 20 is required to get this plugin working with Nx 20

### **Describe alternatives you've considered**

Using Nx 19 until it is supported

**Comment by pawel-twardziak** [comment]
@sudokar Are you willing to raise a PR for that? I am about to do it as I need it in my project - just let me know if you are going to do do it yourself.

**Comment by suds-sky** [comment]
@pawel-twardziak , Please feel free to 😄

**Comment by pawel-twardziak** [comment]
@DominikPieper I've just raised a [PR](https://github.com/nxext/nx-extensions/pull/1136) with NX 20 migration + aligning `solid` package. I am proceeding the rest but maybe @sudokar @suds-sky wants us to bake `https://www.npmjs.com/package/@nxext/solid` ASAP?

**Comment by pawel-twardziak** [comment]
@suds-sky @sudokar done! 8 hour hackathon 🤣 to get this shit done 👯 
@DominikPieper ready to CR 👍

**Comment by sudokar** [comment]
> @suds-sky @sudokar done! 8 hour hackathon 🤣 to get this shit done 👯 @DominikPieper ready to CR 👍

Wow! Great work. Thanks. I should have joined your hackathon 😄  I didn't think it would require a PR with 80 files changed ⭐

**Comment by pawel-twardziak** [comment]
hehe @sudokar for your request there are only 2 commits with around 10 changed files 🤣 the rest changed files are related to the other packages. The migration is for the entire repo 😃

**Comment by sudokar** [comment]
Thanks @pawel-twardziak  and @edbzn, for quickly getting this in 🚀

**Comment by sudokar** [comment]
> Not at all @sudokar 👍 now test it and tell us what are the next issues 😆

Have just tested it @pawel-twardziak  and found that it is still giving me the same issue. Can you check your side and see what happens.

Steps to replicate:

```shell
bunx create-nx-workspace --pm bun
cd my-app
bun add @nxext/solid -d
nx g @nxext/solid:app solid-app
```

Deps:

nx: 20.0.0
@nxext/solid: 20.0.0

**Comment by pawtwa** [comment]
@sudokar  sure thing, will check, thanks for reporting :)

**Comment by pawel-twardziak** [comment]
Ok, I did it :D https://github.com/nxext/nx-extensions/issues/1137 - let's follow up there
