### ISSUE TITLE
Solid: [nx g @nxext/solid:app solid-app] TypeError: implementation is not a function

### ISSUE THREAD

**Issue by pawel-twardziak** [nxext/nx-extensions#1137]
**Describe the bug**
![obraz](https://github.com/user-attachments/assets/6b962bf0-2b22-4793-997b-7770b03e4756)

**To Reproduce**

```
bunx create-nx-workspace --pm bun
cd my-app
bun add @nxext/solid -d
nx g @nxext/solid:app solid-app
```

**Expected behavior**
`solid-app` created

**Additional context**
`bun` package manager

**Comment by pawel-twardziak** [comment]
The problem is, there are no default exports among all `@nxext/...` generators.

When I add the default export like this

![obraz](https://github.com/user-attachments/assets/283f5a0c-6d8b-472b-b22e-85e203b9dfeb)

Everything works fine.

Will fix it.

**Comment by pawel-twardziak** [comment]
@sudokar it is done :)

**Comment by pawel-twardziak** [comment]
@sudokar remember to create the workspace with any preset (Angular, React, what ever...) except None (ts/js) - it is because almost all both official and unofficial plugins do not support it.

![obraz](https://github.com/user-attachments/assets/ad07455e-9c76-433c-bde7-54641dd24d4e)

**Comment by sudokar** [comment]
Thanks @pawel-twardziak , Have just tested it resulted in an error. I think, it is not related to the `nxext` plugin or your changes. It is something from Nx itself, I think.

![image](https://github.com/user-attachments/assets/1955ca77-550e-4f21-89f7-fe29f26369fa)

**Comment by pawel-twardziak** [comment]
> Thanks @pawel-twardziak , Have just tested it resulted in an error. I think, it is not related to the `nxext` plugin or your changes. It is something from Nx itself, I think.
> 
> ![image](https://private-user-images.githubusercontent.com/14125168/376629075-1955ca77-550e-4f21-89f7-fe29f26369fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDQ3MDMsIm5iZiI6MTcyOTAwNDQwMywicGF0aCI6Ii8xNDEyNTE2OC8zNzY2MjkwNzUtMTk1NWNhNzctNTUwZS00ZjIxLTg5ZjctZmUyOWYyNjM2OWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZDM5OWJhODA3MmM2MWFjYTMzMzJmMWI1Y2M2NTNhZjBjYjYwZjhhOTY2ZTk3ZjY2NTVlMmRjZTA0ZTllMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bYpchA2eq8gm9liBWIZdtERRw_5AR2UJF0eVM1WLGNA)

Hi @sudokar yep, this comes from NX itself. There is a new default preset for workspace which is `--preset=ts`.
As I mentioned above, you need to select any other preset excet `ts` while creating a workspace.

**Comment by pawel-twardziak** [comment]
> I think we should re-introduce e2e tests for all packages, that would let us catch this kind of issue. Now only capacitor, ionic-react, and ionic-angular are fully tested.

yes.... there are many custom implementation details that are incompatible with the new NX20.
Currently I am manually testing and fixind all packages. But you are totally right - we need e2e tests to have it automated 👍
