### ISSUE TITLE
[Question] Stencil: pinned `@stencil/core` dependency

### ISSUE THREAD

**Issue by dgonzalezr** [nxext/nx-extensions#1143]
**Describe the bug**

Hi, I wanted to check if there’s a particular reason why the `@stencil/core` dependency has a fixed version.

![CleanShot 2024-10-15 at 12 45 41](https://github.com/user-attachments/assets/ac4e4c43-4fa5-4081-9c36-4a9c9292c21b)

My `@nx` workspace is using the latest `@stencil/core` for our stencil components library, but `@nxext/stencil` v.20.0.1 now installs another version in the node_modules, meaning that our workspace has two versions.

![CleanShot 2024-10-15 at 12 51 19](https://github.com/user-attachments/assets/dc24e632-c9df-4c39-bcad-c915fc40721e)

Our packages are using the right version, but I don't believe that fixing `@stencil/core` to a specific version is the best approach. I might be overlooking something.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by DominikPieper** [comment]
Ah, that's the damn eslint rule ^^' if you fix the version through eslint it takes the current version without a range ^^'

**Comment by pawel-twardziak** [comment]
@DominikPieper  @dgonzalezr yeah, damn, will fix it in the upcoming PR. Thanks for your vigilance @dgonzalezr 👍
