### ISSUE TITLE
https://nxext.dev/ isn't responding

### ISSUE THREAD

**Issue by robinsjovoll** [nxext/nx-extensions#1153]
It's not possible to access https://nxext.dev/  - it gives a connection timeout after a while.

**Comment by pawel-twardziak** [comment]
@edbzn @DominikPieper could you check on it?

**Comment by DominikPieper** [comment]
I’m on it. It’sa communication issue between netlify and Cloudflare. I’m not sure why cause I didn’t changed anything.

**Comment by DominikPieper** [comment]
It should work again. It was a problem between netlify and Cloudflare.
