### ISSUE TITLE
ENOENT: no such file or directory, stat '/C/dev/svelte-test/svelte/apps/test/public' while building/serving a completely new svelte app

### ISSUE THREAD

**Issue by xsintill** [nxext/nx-extensions#122]
I am working on windows 10. nx version used is 10.4.0

steps to reproduce:
- npx create-nx-workspace@latest
- What to create in the new workspace -> choose empty
- CLI to power the Nx workspace -> nx
- Use Nx Cloud -> no
- cd into new dir
- npm install @nxext/svelte --save-dev
- nx g @nxext/svelte:app test
- nx serve test
ENOENT: no such file or directory, stat '/C/dev/svelte-test/svelte/apps/test/public'

copy and cd-ing into the path but changing to 'C:/dev/svelte-test/svelte/apps/test/public' works.
Also tested with the react plugin creating an app. which did not give any problems

package.json

> {
>   "name": "svelte",
>   "version": "0.0.0",
>   "license": "MIT",
>   "scripts": {
>     "nx": "nx",
>     "start": "nx serve",
>     "build": "nx build",
>     "test": "nx test",
>     "lint": "nx workspace-lint && nx lint",
>     "e2e": "nx e2e",
>     "affected:apps": "nx affected:apps",
>     "affected:libs": "nx affected:libs",
>     "affected:build": "nx affected:build",
>     "affected:e2e": "nx affected:e2e",
>     "affected:test": "nx affected:test",
>     "affected:lint": "nx affected:lint",
>     "affected:dep-graph": "nx affected:dep-graph",
>     "affected": "nx affected",
>     "format": "nx format:write",
>     "format:write": "nx format:write",
>     "format:check": "nx format:check",
>     "update": "nx migrate latest",
>     "workspace-schematic": "nx workspace-schematic",
>     "dep-graph": "nx dep-graph",
>     "help": "nx help"
>   },
>   "private": true,
>   "dependencies": {},
>   "devDependencies": {
>     "@nrwl/cli": "10.4.4",
>     "@nrwl/cypress": "10.4.4",
>     "@nrwl/eslint-plugin-nx": "10.4.4",
>     "@nrwl/jest": "10.4.4",
>     "@nrwl/tao": "10.4.4",
>     "@nrwl/workspace": "10.4.4",
>     "@nxext/svelte": "^10.1.2",
>     "@types/jest": "26.0.8",
>     "@types/node": "~8.9.4",
>     "@typescript-eslint/eslint-plugin": "4.3.0",
>     "@typescript-eslint/parser": "4.3.0",
>     "cypress": "^5.5.0",
>     "dotenv": "6.2.0",
>     "eslint": "7.10.0",
>     "eslint-config-prettier": "6.0.0",
>     "eslint-plugin-cypress": "^2.10.3",
>     "eslint-plugin-svelte3": "^2.7.3",
>     "jest": "26.2.2",
>     "prettier": "2.1.2",
>     "svelte": "^3.29.0",
>     "svelte-jester": "^1.1.5",
>     "svelte-preprocess": "^4.4.2",
>     "ts-jest": "26.4.0",
>     "ts-node": "~7.0.0",
>     "tslint": "~6.0.0",
>     "typescript": "~4.0.3"
>   }
> }

workspace.json

> {
>   "version": 1,
>   "projects": {
>     "test": {
>       "projectType": "application",
>       "root": "apps/test",
>       "sourceRoot": "apps/test/src",
>       "architect": {
>         "build": {
>           "builder": "@nxext/svelte:build",
>           "options": {
>             "outputPath": "dist/apps/test",
>             "entryFile": "apps/test/src/main.ts",
>             "tsConfig": "apps/test/tsconfig.app.json",
>             "assets": ["apps/test/public"]
>           },
>           "configurations": {
>             "production": {
>               "dev": false
>             }
>           }
>         },
>         "serve": {
>           "builder": "@nxext/svelte:build",
>           "options": {
>             "outputPath": "dist/apps/test",
>             "entryFile": "apps/test/src/main.ts",
>             "tsConfig": "apps/test/tsconfig.app.json",
>             "assets": ["apps/test/public"],
>             "watch": true,
>             "serve": true
>           },
>           "configurations": {
>             "production": {
>               "prod": true
>             }
>           }
>         },
>         "lint": {
>           "builder": "@nrwl/linter:lint",
>           "options": {
>             "linter": "eslint",
>             "tsConfig": "apps/test/tsconfig.app.json",
>             "exclude": ["**/node_modules/**", "!apps/test/**/*"]
>           }
>         },
>         "test": {
>           "builder": "@nrwl/jest:jest",
>           "options": {
>             "jestConfig": "apps/test/jest.config.js",
>             "passWithNoTests": true
>           }
>         }
>       }
>     },
>     "test-e2e": {
>       "root": "apps/test-e2e",
>       "sourceRoot": "apps/test-e2e/src",
>       "projectType": "application",
>       "architect": {
>         "e2e": {
>           "builder": "@nrwl/cypress:cypress",
>           "options": {
>             "cypressConfig": "apps/test-e2e/cypress.json",
>             "tsConfig": "apps/test-e2e/tsconfig.e2e.json",
>             "devServerTarget": "test:serve",
>             "baseUrl": "http://localhost:4200"
>           },
>           "configurations": {
>             "production": {
>               "devServerTarget": "test:serve:production"
>             }
>           }
>         },
>         "lint": {
>           "builder": "@nrwl/linter:eslint",
>           "options": {
>             "lintFilePatterns": ["apps/test-e2e/**/*.{js,ts}"]
>           }
>         }
>       }
>     }
>   },
>   "cli": {
>     "defaultCollection": "@nrwl/workspace"
>   }
> }

**Comment by DominikPieper** [comment]
The new version 10.1.3 should fix this :-)
