### ISSUE TITLE
Publishing latest (svelte) package

### ISSUE THREAD

**Issue by cassshh** [nxext/nx-extensions#126]
Hi,

First of all, I just want to thank you for your work.
And by no means I want this to come over as pressure.

This is more of a question than an 'issue';
I'm wondering when the latest version of `@nxext/svelte` is being published (to npmjs)?
As I'm waiting for #110 to become available for my side-project 😄 

Since the other packages (`@nxext/stencil` and now `@nxext/tailwind`) were updated this week, I was hoping `@nxext/svelte` would arrive soon.
<img width="451" alt="Screenshot 2020-12-04 at 11 34 00" src="https://user-images.githubusercontent.com/10263056/101153842-396bfb80-3625-11eb-94bc-5cb70c9f427a.png">

Thanks again for your time and effort!

**Comment by DominikPieper** [comment]
Hi,

sorry about that. You're right, I stumbled on another bug but now I released a patch version with that changes in place as well.

Please try version 10.1.3 :-)

**Comment by cassshh** [comment]
No worries.
Just tested the latest version, and my app now builds correctly 🙂 
Cheers!
