### ISSUE TITLE
files and folders not copied from public to dist

### ISSUE THREAD

**Issue by xsintill** [nxext/nx-extensions#128]
Steps to reproduce 

os used windows 10
nx version used 10.4.4
nxext/svelte version used 10.1.3

- Creating a brand new svelte app in a blank nx workspace
- nx serve

Everything builds without error but when navigating to the site it can not start giving the following error:
```
404 Not Found

C:\dev\svelte\nzb-browse\dist\apps\nzb-browse\index.html

(rollup-plugin-serve)
```
This is because the files in public are not being copied over to the dist folder.

To make it work for me I changed the convertCopyAssetsToRollupOptions function in node_modules\@nxext\svelte\src\builders\utils\normalize.js to the following: 
```
function convertCopyAssetsToRollupOptions(outputPath, assets) {
    return assets
        ? assets.map((normalizedCopyAssetOption) => ({            
            src: path_1.join(normalizedCopyAssetOption.input, normalizedCopyAssetOption.glob).replace(/\\/g, '/'),
            dest: path_1.join(outputPath, normalizedCopyAssetOption.output).replace(/\\/g, '/'),
        }))
        : undefined;
}
```
I am not sure if this breaks anything on other configurations or operating systems but after this the rollup-plugin-copy did copy over whatever was in the public directory to the correct place and the basic app started working.

**Comment by DominikPieper** [comment]
Does this still exist for you with the newer versions?
