### ISSUE TITLE
Path can not be used when generating Svelte-App

### ISSUE THREAD

**Issue by alexandermikuta** [nxext/nx-extensions#130]
**Actual:**

Error when generating an svelte-app with a full path, e.g. `nx g @nxext/svelte:app products/ui`.
Error-message is `Cannot read property 'architect' of undefined`

**Expected:**

like in other existing nx-plugins would be creating the app with name `products-ui` inside of folder `apps/products`. This would make structuring the monorepo a lot easier, e.g. when building micro-apps with one folder for the api-microservice and the other with the svelte-microfrontend

**Comment by DominikPieper** [comment]
New release
