### ISSUE TITLE
feat: option to use svelte@next when generating app

### ISSUE THREAD

**Issue by alexandermikuta** [nxext/nx-extensions#131]
I would be nice to have the option when generating an app with `nx g @nxext/svelte:app my-app` to be able to use `svelte@next
` instead.

**Comment by DominikPieper** [comment]
I'll wait for the public beta I think. Every time I looked into svelte@next the last times the build process changed. From rollup to snowpack, now it's vite as a build system.

**Comment by DominikPieper** [comment]
Highly experimental yet, there will be breaking changes https://github.com/nxext/nx-extensions/tree/v11.0.0-next-Sveltekit
