### ISSUE TITLE
nxext/svelte live reload giving ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by softgripper** [nxext/nx-extensions#132]
Getting ERR_CONNECTION_REFUSED error from livereload when accessing the svelte app on default settings (localhost:4200).

![livereload](https://user-images.githubusercontent.com/26377893/101867006-57f66780-3bce-11eb-8d9c-7db72598926f.png)

Fresh nx-workspace 
Fresh nxext/svelteapp
Fresh nrwl/reactapp

I'm starting the app with

```bash
nx serve svelte-app --watch
```

The rollup bundler is detecting file changes, and is writing the bundle when svelte files change.

**Comment by DominikPieper** [comment]
Does this works with the newer versions for you?
