### ISSUE TITLE
Support NX 11.0

### ISSUE THREAD

**Issue by sforner405** [nxext/nx-extensions#134]
Hi,
just updated the nx workspace to 11. It seems the stencil extension is not working anymore.

If I want to build a buildable lib I get the following error:

> nx run stencil-library:build
Cannot read property 'build' of undefined

It is just a new generated stencil lib.

**Comment by DominikPieper** [comment]
Hi, yes the stencil plugins version match the nx versions. The last released is 10.x and that's compatible with Nx 10. The Nx11 compatible version will be released soon, already working on the migration. Hopefully at weekend I'll be done und release the version 11

**Comment by sforner405** [comment]
Thanks, for the reply.
As far as I can see the problem is the change in handling architect elements in context target, as they are empty right now.

**Comment by DominikPieper** [comment]
Yes, that's cause the internal api changed. Nrwl prepared some migrations for that already, so it's not hard to change it. :)

**Comment by DominikPieper** [comment]
Update for version 11 is published
