### ISSUE TITLE
[Svelte] Window build issue due path issue for sveltePreprocessConfig build option

### ISSUE THREAD

**Issue by b-barry** [nxext/nx-extensions#139]
Hello,

Thanks for the Svelte plugin, it is saving a lot of time.
I am setting an sveltePreprocessConfig for adding tailwind and purgecss ( could be cool btw to have this option because you have added the tailwind plugin).

My path is: "apps/my_project/preprocess.js" 
The file contains:
```js
function getPreprocess() {
  const path = require("path");

  const purgecss = require("@fullhuman/postcss-purgecss")({
    content: ["./src/**/*.html", "./src/**/*.svelte"],
    whitelistPatterns: [/svelte-/],
    defaultExtractor: (content) => content.match(/[A-Za-z0-9-_:/]+/g) || [],
  });

  return {
    postcss: {
      plugins: [
        require("tailwindcss")(
          path.resolve("./apps/my_project/tailwind.config.js")
        ),
        require("autoprefixer"),
        // purgecss,
      ],
    },
  };
}

module.exports = getPreprocess;
```

On mac, it is working fine but on window, I am not able to run the builder because it is can not find the module.
I think it is due to the / 

version:^10.1.3

**Comment by DominikPieper** [comment]
Svelte is on the list for the tailwind plugin. Fighting with the path problems on windows as well. Did you tried today's version 11? (for NX 11)

**Comment by b-barry** [comment]
Thanks for the quick answer.
I could migrate yet on the version 11. 
Could try it to validate if I got the issue

**Comment by b-barry** [comment]
I migrated everything on Nx11 and tested on window, I don't have any issues

**Comment by DominikPieper** [comment]
Great to hear :)
