### ISSUE TITLE
[Svelte][feature request] Schematic to generate a lib

### ISSUE THREAD

**Issue by b-barry** [nxext/nx-extensions#140]
I think it will cool to be able to generate lib like for Stencil and be able to build them in production (maybe we could use @web/packages plugin of Nx).

I am using the version: ^10.1.3

**Comment by DominikPieper** [comment]
That'll be the next step. Worked today on the Nx11 update, hopefully start to work on this tomorrow while fighting some problems with windows builds

**Comment by b-barry** [comment]
I tried to build manually using web package but getting issue in the svelte app about the tsconfig paths that it is not valid

**Comment by DominikPieper** [comment]
@nrwl/web unfortunately uses an old rollup version. Tried that first as well but the old rollup version doesn't seem to work good the svelte

**Comment by b-barry** [comment]
Yes, I forgot about it. I downgraded the version of the package to make them work. It was a pain in the ass

**Comment by DominikPieper** [comment]
That's the reason why I use a custom builder. @nrwl/web would be cool, like the react package but it won't work correctly. Maybe someday.

**Comment by b-barry** [comment]
Thanks @DominikPieper  for the work. I made a custom setup so I can migrate.

**Comment by tanepiper** [comment]
@DominikPieper Any news on this being published? Is saw it here in the repo, but it's not in the npm module?
