### ISSUE TITLE
building stencil library not possible - dist folder not generated

### ISSUE THREAD

**Issue by kerosin** [nxext/nx-extensions#142]
Hi there,

this might not been an issue per se, more a question.
I'm not able to build my nx stencil library to create a dist folder.

Here are the steps I took:
1. create a fresh nx 11 workspace ```npx create-nx-workspace@latest my-workspace``` with a new Angular app
2. installing nxext ```npm install -D @nxext/stencil```
3. generating a stencil library via ```nx g @nxext/stencil:lib web-components```
4. making stencil lib buildable ```nx generate @nxext/stencil:make-lib-buildable web-components```
5. added output target for angular ```nx g @nxext/stencil:add-outputtarget web-components```
6. added ```WebComponentsAngularModule``` from ```@my-workspace/web-components-angular``` to *app.module.ts*

If I now run ```nx build my-app``` I receive an error
`Error: libs/web-components-angular/src/lib/web-components-angular.module.ts:3:38 - error TS2307: Cannot find module '@my-workspace/web-components/loader' or its corresponding type declarations.`

At a closer look there is no *dist* folder at /libs/web-components
So I called ```nx run web-components:build```
```
[56:10.7]  build, web-components, prod mode, started ...
[56:10.7]  transpile started ...
[56:10.8]  transpile finished in 104 ms
[56:10.8]  generating angular-library started ...
[56:10.9]  generate angular-library finished in 6 ms
[56:10.9]  build finished in 132 ms
```
but there is still no dist folder created.

How can I build my stencil library properly?

**Comment by DominikPieper** [comment]
Hi,
oh you're right. That's a bug in the make-buildable-schematic. Please add this to your stencil.config.ts, I'll fix the schematic.

`{
      type: 'dist',
      esmLoaderPath: '../loader',
      dir: '../../dist/libs/web-components/dist',
    },
    {
      type: 'docs-readme'
    },
    {
      type: 'www',
      dir: '../../dist/libs/web-components/www',
      serviceWorker: null // disable service workers
    },` 

The default output-targets are not added

**Comment by kerosin** [comment]
Okay initially my stencil.config.ts looked like this
```
import { Config } from '@stencil/core';
import { sass } from '@stencil/sass';
import {
  angularOutputTarget,
  ValueAccessorConfig
} from '@stencil/angular-output-target';

const angularValueAccessorBindings: ValueAccessorConfig[] = [];

export const config: Config = {
  namespace: 'web-components',
  taskQueue: 'async',
  plugins: [sass()],
  outputTargets: [
    angularOutputTarget({
      componentCorePackage: '@fls-mobile/web-components',
      directivesProxyFile:
        '......libsweb-components-angular/src/generated/directives/proxies.ts',
      valueAccessorConfigs: angularValueAccessorBindings
    })
  ]
};
```

and i changed the outputTargets to the value you provided

the strange folder `'......libsweb-components-angular/src/` is now on *dist/libs/web-components*

I still get an error about the missing loader 
`Error: libs/web-components-angular/src/lib/web-components-angular.module.ts:3:38 - error TS2307: Cannot find module '@my-workspace/web-components/loader' or its corresponding type declarations.`

**Comment by DominikPieper** [comment]
Maybe some clarification about what's going ideally on.

The dist of web-components contain after build the web components. That's where the loader folder should appear as well.
The web-components-angular contains glue-code for the web-components and Angular. They're both needed

**Comment by DominikPieper** [comment]
The glue code will be generated in the *-angular project. That's what will be packaged into that project

**Comment by kerosin** [comment]
Manually setting the path to `import { defineCustomElements } from '../../../../dist/libs/web-components/loader';` on the `web-components-angular.module.ts` fixed the behaviour. Is that the expected way to store it on the global dist folder instead to the workspace folder?

**Comment by DominikPieper** [comment]
What do you mean by "Instead of the workspace folder?" Ideally, it should be imported by the @yourProject/web-components/leader

**Comment by kerosin** [comment]
If I run `nx build web-components` the loader and dist files are stored to the global dist folder
![grafik](https://user-images.githubusercontent.com/804836/103613433-d7a1f880-4f26-11eb-923a-194598881853.png)

So the loader files are not accessible via `@my-workspace/web-components/loader`.

That was the reason I changed the path on the `web-components-angular.module.ts` to the global dist folder.
If I hear this correctly, this is unintentional behavior during setup.
Should I create a repo to clear things up? 😉

**Comment by DominikPieper** [comment]
A repo would be great. Yes that's unintended and should be handled by the repo correctly (or better by typescript through the config)

**Comment by kerosin** [comment]
Okay there you go: https://github.com/kerosin/nx-stencil-example

The steps to create it are basically the same as on the first post

**Comment by DominikPieper** [comment]
Hey, I took a look and prepared a PR for that repo with the fix. Basically the make-buildable builder had the bug, that the loader wasn't added to the tsconfig. With that, nx wasn't able to find the loader workspace imports for the angular-module.

**Comment by kerosin** [comment]
thank you very much! I will close this issue
