### ISSUE TITLE
critical documetation bug

### ISSUE THREAD

**Issue by davidmoshal** [nxext/nx-extensions#151]
Hi, not sure what control you have over npmjs, but that page erroneously suggests that this plugin should be installed as a dev dependency:

https://www.npmjs.com/package/@nxext/svelte

`npm install @nxext/svelte --save-dev`  

should be:
`npm install @nxext/svelte --save`

Thanks for this plugin, excited to be using it!

**Comment by DominikPieper** [comment]
Hi,

why do you think it's an error? The plugin is exactly that, a dev dependency. It just adds features for the developer which shouldn't be part of the result

**Comment by davidmoshal** [comment]
I agree, it should be a dev dependency, but for some reason it fails unless it's a non-dev dependency.

**Comment by DominikPieper** [comment]
Mhh I can't reproduce that. What's the environment here? Os? nom or yarn (or something else)?

Did a quick test on a new empty nx workspace and all working with it as a dev dependency

**Comment by davidmoshal** [comment]
npm

**Comment by DominikPieper** [comment]
Do you have a repository where I can check with? I did some experiments with npm repositories, and I can't see a problem. (And it shouldn't be one cause --save-dev is correct, it's a dev dependency)
