### ISSUE TITLE
Compiled files not restored when build cache is up to date.

### ISSUE THREAD

**Issue by FortinFred** [nxext/nx-extensions#156]
When the compile cache is up to date, the compiled files are not restored to the build directory for a stencil component library.

Version: 10.3.0

![image](https://user-images.githubusercontent.com/17817939/105415507-cdf6e100-5c06-11eb-9cc4-55deffd7e5f4.png)

Workaround:
Use the --skip-nx-cache

nx build web-components --skip-nx-cache

**Comment by FortinFred** [comment]
Anything on this ?!

**Comment by doliG** [comment]
I have the same concern.

**Comment by DominikPieper** [comment]
Not really yet. That's something the plugin doesn't do manually, it's done by nx automatically so I'm not sure where to hook in or look at
