### ISSUE TITLE
Adding svelte preprocessors to rollup config?

### ISSUE THREAD

**Issue by tanepiper** [nxext/nx-extensions#163]
I've tried to follow other examples in the issues here, but haven't been able to figure it out.

I have a custom rollup config already, but I'm trying to add a markdown library (https://mdsvex.com/) to my app (I also tried with https://github.com/AlexxNB/svelte-preprocess-markdown but had the same issue).

The problem is in both their examples they add the function directly to the svelte rollup plugin, which doesn't seem possible - and not possible to have multiple.

I've tried adding it to a preprocessor script, but it's not clear where I add the extensions. I ended on below - nothing breaks but it's not rendering as expected, so I assume it's not being loaded?  (I tried using it in the replace, but that seems to be a different set of options)

```
const { mdsvex } = require('mdsvex')

function setSveltePreprocessOptions(options) {
  return {
    typescript: {
      extensions: [
        '.svelte',
        '.svx'
      ],
      plugins: [
        mdsvex({extensions: ['.svelte', '.svx']})
      ]
    }
  };
}

module.exports = setSveltePreprocessOptions;
```

**Comment by DominikPieper** [comment]
I added a hopefully easier way to do the configurations. There's an example in the docs now.

**Comment by tanepiper** [comment]
@DominikPieper Great! I've not had a chance to update yet but I'll have a look as this will help with me getting my E2E tests up for Formula. Thanks

**Comment by DominikPieper** [comment]
I'll close this for now, reopen if the problem still exist or open a new after you tried the update :-)
