### ISSUE TITLE
Stencil: Malke lib publishable

### ISSUE THREAD

**Issue by philippone** [nxext/nx-extensions#168]
Hi,

my goal is to build a component library with Stencil that publish each component separately to npm. 

To be more generic in this issue, I would like to distribute a library outside of the monorepo. 

Nx supports `--publishable` option for the `library` generator for Angular, React and Node: https://nx.dev/latest/node/structure/buildable-and-publishable-libraries#publishable-libraries

Are there any plans to support the `--publishable` option?

Usage:
`nx g @nxext/stencil:library my-app --publishable --importPath @myorg/mylib`

Maybe, we could add something similar to [`make-lib-buildable`](https://github.com/nxext/nx-extensions/tree/main/packages/stencil/src/schematics/make-lib-buildable)?

**Comment by DominikPieper** [comment]
Sounds like a good idea. I hadn't it on the list yet, thank you.

**Comment by mburger81** [comment]
Are there news?
