### ISSUE TITLE
Stencil Library: Tests fails if component is using another library from nx workspace

### ISSUE THREAD

**Issue by kerosin** [nxext/nx-extensions#182]
Hey,

I run into errors if a stencil component uses a library from the nx workspace.
The build itself (`nx build web-components`) is totally fine, but if I run tests (`nx test web-components`) I get an error about a missing module:
```
 FAIL  libs/web-components/src/components/my-component/my-component.spec.ts
  ● Test suite failed to run

    Cannot find module '@my-workspace/lib-a' from 'src/components/my-component/my-component.tsx'

    Require stack:
      src/components/my-component/my-component.tsx
      src/components/my-component/my-component.spec.ts

      2 | 
      3 | import { format } from '../../utils/utils';
    > 4 | import { libA } from '@my-workspace/lib-a';
        | ^
      5 | 
      6 | @Component({
      7 |   tag: 'my-component',

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (src/components/my-component/my-component.tsx:4:1)

```

Reproduce:
- checkout https://github.com/kerosin/nx-stencil-example
- call `nx test web-components`

**Comment by kerosin** [comment]
@DominikPieper any idea what the reason might be?

I tried to add a custom testing configuration to the stencil.config.ts where the nx jest.preset.js is loaded as preset, but this results in further errors :(

**Comment by DominikPieper** [comment]
Is it a buildable or not buildable dependency? The whole dependency stuff unfortunately is error prone at the moment :-(

**Comment by kerosin** [comment]
A not buildable dependency.
But because the build of the stencil components itself is fine, it must be related to the tsconfig or jest setup of stencils internals I guess...

**Comment by kerosin** [comment]
Topic might be related to https://github.com/ionic-team/stencil/issues/1307

I found a temporary fix. I edited *stencil.config.ts* and manually added the other project
```
...
import { moduleNameMapper } from '@stencil/core/testing/jest-preset';

export const config: Config = {
  ...
  testing: {
    moduleNameMapper: {
      ...moduleNameMapper,
      '@my-workspace/lib-a': '<rootDir>/../lib-a/src/index.ts',
    },
  },
...
};
```
Not an ideal solution, but works for now
