### ISSUE TITLE
Svelte library build only generate the bundle.js file

### ISSUE THREAD

**Issue by FrancoisDF** [nxext/nx-extensions#198]
When creating and building a Svelte library, Svelte `build` only generates a single file in the dist folder.
When doing the same with an angular library that uses `@nrwl/angular:package`, we get all the `.d.ts` files and the `package.json` that ease the deployment of the library.
Is that expected? Is there a way to at least copy the `package.json` file in the build process?

**Comment by FrancoisDF** [comment]
Actually, using `@nrwl/web:package` let you correctly build the svelte library:
```json
{
  "build": {
    "builder": "@nrwl/web:package",
    "options": {
      "outputPath": "dist/libs/svelte",
      "tsConfig": "libs/svelte/tsconfig.lib.json",
      "project": "libs/svelte/package.json",
      "entryFile": "libs/svelte/src/index.ts",
      "assets":[
        "libs/svelte/src/svelte"
      ],
      "buildableProjectDepsInPackageJsonType": "dependencies"
    }
  }
}
```

**Comment by DominikPieper** [comment]
@FrancoisDF @nrwl/web now supports rollup 2 ootb and I'm working on a bigger refactoring to get rid of the own executors completely in favor of the nrwl one.

**Comment by Jordan-Hall** [comment]
Maybe we move this to vite library bundle. I'll need to write some unit test and make sure it's 100% there. But it does the package.json, need to check d.ts file

**Comment by DominikPieper** [comment]
Done the transition to vite
