### ISSUE TITLE
Importing typescript libraries in a svelte project

### ISSUE THREAD

**Issue by DiogoVCS** [nxext/nx-extensions#202]
I have a project where i need to import typescript libraries using the plugin @nrwl/web from within a svelte application. It gives the following error:

```bash
Error during bundle: Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
Bundle failed.
```

I have created a simple example, with the error reproduced [here](https://github.com/DiogoVCS/test-svelte-typescript-library). 

If i am importing a javascript library, it works fine. Might be some rollup config, but i was not able to correct the issue.

**Comment by krcourville** [comment]
I think I'm running into a similar issue.  Good to confirm it's not just me.  Will dig a little more.

```
Error during bundle: The keyword 'public' is reserved (Note that you need plugins to import files that are not JavaScript)
```

My project definition looks like:

```json
  "projects": {
    "my-lib": {
      "root": "libs/my-lib",
      "sourceRoot": "libs/my-lib/src",
      "projectType": "library",
      "targets": {
        "lint": {
          "executor": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/my-lib/**/*.{ts,tsx,js,jsx}"]
          }
        },
        "test": {
          "executor": "@nrwl/jest:jest",
          "outputs": ["coverage/libs/my-lib"],
          "options": {
            "jestConfig": "libs/calc-parse/jest.config.js",
            "passWithNoTests": true
          }
        }
      }
    },
```

**Comment by DiogoVCS** [comment]
I just managed to resolve this issue, and its not related with the svelte plugin, I'll leave here the solution for others that can encounter this error and just close the issue:

Add a ```babel.config.js``` file at the root of the Nx Workspace, it can be as simple as this one:

```javascript
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
  ],
};
```

And don't forget to install the necessary packages:

```bash
npm install @babel/core @babel/preset-env --save-dev
```

And for running tests make use of the package ```babel-jest```.
The integration of the library should now work properly

related:
[https://blog.nrwl.io/gatsby-support-custom-workspace-layouts-and-more-in-nx-9-4-497ae105bf4](Custom Babel configuration)
[https://github.com/nrwl/nx/issues/1721](how to use custom .babelrc or babel.config.js with @nrwl/react)
