### ISSUE TITLE
[Svelte] historyApiFallback should be enabled for serve command

### ISSUE THREAD

**Issue by ball6847** [nxext/nx-extensions#208]
In development, when we use routing with history strategy. It's necessary to fallback any non existing path to index.html, to let svelte handle the page.

### Current Behavior:

After running `nx serve`, any direct navigation from browser to non existing page will lead to devserver's 404 file not found page

### Expected Behavior: 

After running `nx serve`, any direct navigation from browser to non existing page, should load index.html and bootstrap svelte application.

From https://github.com/nxext/nx-extensions/blob/main/packages/svelte/src/executors/utils/rollup-options.ts#L109
We need extra options for `serve` plugin, adding `historyApiFallback: true` should solve the problem

Thanks for your effort creating this.

**Comment by DominikPieper** [comment]
There’sa Patch Release for that now

**Comment by ball6847** [comment]
Updated to new version and work as expected

Thank you.
