### ISSUE TITLE
NX with svelte-kit

### ISSUE THREAD

**Issue by Thebigbignooby** [nxext/nx-extensions#227]
As I understand it nxext/svelte currently supports only the "old" svelte but not svelte-kit ?

I'm wondering if anyone is working on this at the moment?

**Comment by DominikPieper** [comment]
There's a package @nxext/sveltekit right now, but doesn't reflect all changes of the last weeks after Sveltekit entered the public beta yet. https://www.npmjs.com/package/@nxext/sveltekit

**Comment by Thebigbignooby** [comment]
I just found this package and came back to post the link but I see you beat me to it :p

thanks!

So, what needs to be done to bring this package up to date? 

And are there simple steps I can take to use the latest sveltekit after having generated my nx app with the above package?

cheers

**Comment by DominikPieper** [comment]
It is mostly just the code template files in the app generator. If you want you can just generate an Sveltekit application and migrate the files to the template files. You just have to watch the tsconfig, it use the base tsconfig
