### ISSUE TITLE
Enable CORS for dev-server

### ISSUE THREAD

**Issue by sbolz** [nxext/nx-extensions#228]
I'd like to start the dev-server of a Svelte project with CORS enabled, so I can access the server from a different origin.

The `rollup-plugin-serve` has an option to pass arbitrary headers, but it is currently not used by the @nxext/svelte executor.
It would be great, if either an "headers" options could be passed directly to the rollup-plugin-serve, or alternatively a "cors" option that will just set the according `'Access-Control-Allow-Origin': '*'` header.

As an alternative, I tried to overwrite the "serve" plugin with a custom rollup config. But this didn't work as expected, because the function `serve()` of the `rollup-plugin-serve` already starts a server on first invokation and the second invocation in the custom rollup config throws an error, saying that the port is already in use.

Context, as to why I need CORS so badly:
I'm starting to develop in a microfrontend environment with _single-spa_. In this environment, the root application (e.g. running on port on 3000) calls out to other microfrontend servers on different ports. Because the port is part of the _origin_, this already counts as a cross-origin request.

**Comment by DominikPieper** [comment]
There's a option now to set headers :-)

**Comment by sbolz** [comment]
Wow, that was fast! 🚀 
Thank you so much 👍

**Comment by DominikPieper** [comment]
There's a new release 11.3.2 . Please let me know if there's any problem
