### ISSUE TITLE
Built packages contain spec files

### ISSUE THREAD

**Issue by AgentEnder** [nxext/nx-extensions#239]
**Describe the bug**
Built packages include **/*.spec.ts files.

**To Reproduce**
Run `nx build ...` for the project.

**Expected behavior**
Built packages are javascript / json / .d.ts files + any other required files, without spec files or other dev dependencies.

**Additional context**
nrwl/nx#5566 fixes this for new plugins, older ones need to implement behavior.

see tinesoft/nxrocks#54 for needed change

**Comment by DominikPieper** [comment]
Thanks for the bug, I'll add it soon :-)
