### ISSUE TITLE
gitignore for www directory or build to dist

### ISSUE THREAD

**Issue by luchsamapparat** [nxext/nx-extensions#24]
When starting the app via `nx serve`, stencil compiles the app to `/apps/my-app/www`. It would be great if the workspace is 

a) either configured to put those build files into `/dist`
b) or adds a `.gitignore` file to ignore the `www` directory

I'm not sure if the Stencil API allows a).

*Steps for Reproduction* 

```sh
create-nx-workspace my-workspace
npm install @nxext/stencil --save
nx g @nxext/stencil:app my-app
git add .
git commit -m "initial commit"
npm start my-app
```

Thanks a lot, btw, for creating this project!

**Comment by DominikPieper** [comment]
Hey,
the `www` is something the stencil compiler does by default. You can try to configure the output target in your `stencil.config.ts. That's nothing I'm doing and I'd like to stick with the default/stencil configuration here.

**Comment by DominikPieper** [comment]
With actual versions the builder target is in `dist`. Is this okay and serves your needs?
I think I misunderstood something last comment I did

**Comment by luchsamapparat** [comment]
Hi,

sorry, that I didn't respond to your last post yet. I put my Stencil project aside to work on other things.

I'm not sure what you mean by "actual versions"?

When following the steps of my origin post, after running the app for the first time, you end up with 44 untracked files in your repository:

![image](https://user-images.githubusercontent.com/875017/86400042-38b2f000-bca8-11ea-8b79-238a181c5df2.png)

As these are build artefacts, they should either be generated in the `/dist` directory or at least be ignored via `.gitignore`.

Of course, it's easy to do the latter manually, but it would be a nice improvement if `@nxext/stencil` generated a `.gitignore` file automatically when generating a new app via `nx g @nxext/stencil:app`.

**Comment by DominikPieper** [comment]
What version are you using? My confusion comes from, the build process builds per default into `dist/apps/<appname>` since a few versions. 

```
$ nx run stencil-pwa:build
[50:14.5]  @stencil/core v1.14.0 🏒
[50:16.6]  build, app, prod mode, started ...
[50:16.6]  transpile started ...
[50:17.6]  transpile finished in 960 ms
[50:17.6]  copy started ...
[50:17.6]  generate lazy started ...
[50:19.5]  copy finished (1243 files) in 1.93 s
[50:40.4]  generate lazy finished in 22.78 s
[50:40.4]  build finished in 23.81 s
```

```
$ ls dist/apps/stencil-pwa/www
assets           build            host.config.json index.html       manifest.json
```

**Comment by luchsamapparat** [comment]
🤔 Weird, running the same command (`nx run my-app:build`), a `dist/apps/my-app` directory is created, however it is empty. In addition, `apps/my-app/www` is also created and it contains all the files as in your example.

Here's the repository I used for my test:
https://github.com/luchsamapparat/nx-workspace-stencil

```
@nrwl/workspace - 9.5.1
@nxext/stencil - 0.1.3
@stencil/core - ^1.14.0
```

**Comment by DominikPieper** [comment]
Is the repo public? I can't reach it

**Comment by luchsamapparat** [comment]
Sorry, I accidentally made it private. Should be accessible now

**Comment by DominikPieper** [comment]
Hey, I tried your repo and can't reproduce the issue. Works as expected building into dist. WHat OS do you use? Windows? Mac? Linux? Mayve a platform problem

**Comment by DominikPieper** [comment]
There's a new release. I hope it works for you :-)

**Comment by luchsamapparat** [comment]
The latest release of `@nxext/stencil` indeed fixes the issue 🥳
