### ISSUE TITLE
Dependency Chaos

### ISSUE THREAD

**Issue by DaSchTour** [nxext/nx-extensions#240]
**Describe the bug**
There are some weird dependencies.
For example `@nxext/tailwind` requires `@nxext/svelte` which needs a lot other peerDependencies.
Additionally `@nxext/stencil` requires `@nxext/tailwind@^11.2.0` which does not exist in NPM.
Currently I get a lot of warnings related to missing peer dependencies because of this.

**Expected behavior**
Clean and working dependencies.

**Comment by DominikPieper** [comment]
The peerDependencies are not all needed, if you don't use all functionalities. e.g. the tailwind package (which will be removed soon) have both as a peer dependency cause they can generate the Tailwind config for stencil and svelte, but you don't need both to get them working. It'll need stencil for the stencil generator and svelte for the svelte generator

**Comment by DaSchTour** [comment]
Yeah but currently `@nxext/svelte` seams to be a direct dependency of `@nxext/tailwind` so it is always installed. I'm not using svelte and haven't installed it but I see that the peerDependencies of `@nxext/svelte` are missing
