### ISSUE TITLE
Couldn't find package "@next/vite@12.0.0" required by "@nxext/svelte" on the "npm" registry

### ISSUE THREAD

**Issue by maierson** [nxext/nx-extensions#248]
**Describe the bug**
Trying to install with `yarn add @nxext/svelte -D` and it fails with the error in the title.

**To Reproduce**
See above

**Expected behavior**
The extension installs and is available for use.

**Additional context**

**Comment by DominikPieper** [comment]
Thanks there was a typo in the dependency I missed. Fixed with 12.0.1
