### ISSUE TITLE
bug(stenciljs:lib): serve on stenciljs lib does not work as expected

### ISSUE THREAD

**Issue by mburger81** [nxext/nx-extensions#256]
**Describe the bug**
we have created an empty workspace with nx cli and added an stenciljs lib with
`nx g @nxext/stencil:lib my-lib --publishable --importPath=@abc/def`

But running 
`nx serve my-lib`
the lib is not served as expected, is there a way to run and debug the lib as we do on plane stencil cli?

running serve it is opening a page with the files in the dist folder
![image](https://user-images.githubusercontent.com/3778892/120157901-cc13de80-c1f3-11eb-98fc-31e870ad6289.png)

**Comment by DominikPieper** [comment]
The easiest fix here ist, add the 'www' target and an index.html. That should be all to work
