### ISSUE TITLE
Issue with the sveltekit package

### ISSUE THREAD

**Issue by Jojoker33** [nxext/nx-extensions#275]
**Describe the bug**
when trying to generate a new svelte kit project  an error is shown : 
*Package "@nxext/sveltekit" was found but does not support schematics.*

**To Reproduce**
  nx g @nxext/sveltekit:app newApp

**Expected behavior**
Being able to create a svelte-kit app in order to easily to change our existing svelte app into svelte kit

**Comment by DominikPieper** [comment]
Hey, what version of Nx are you using?

**Comment by Jojoker33** [comment]
Hi, i used the verion 10.4.7

**Comment by DominikPieper** [comment]
That won't work. The Sveltekit (and all other Nxext plugins) use Nx version 12.x.x

**Comment by Jojoker33** [comment]
I will update my version, thank you for your time and helps

**Comment by Jojoker33** [comment]
It's properly working now, thank you for your time, and sorry for that
