### ISSUE TITLE
Stencil: Storybook stories written in TypeScript not working

### ISSUE THREAD

**Issue by SebastianSchenk** [nxext/nx-extensions#339]
**Describe the bug**
When adding Storybook via `nx g @nxext/stencil:storybook-configuration my-lib`, a `my-component.stories.jsx` will be generated when creating a new component. Running this story works fine without any errors. However,  changing this file type to `.tsx` will lead to the following error when rendered in Storybook: 

```
h is not defined
ReferenceError: h is not defined
    at Primary (http://localhost:4400/main.iframe.bundle.js:1964:3)
    at finalStoryFn (http://localhost:4400/vendors~main.iframe.bundle.js:16423:32)
    at http://localhost:4400/vendors~main.iframe.bundle.js:13056:21
    at http://localhost:4400/vendors~main.iframe.bundle.js:14980:16
    at http://localhost:4400/vendors~main.iframe.bundle.js:13546:16
    at http://localhost:4400/vendors~main.iframe.bundle.js:13563:26
    at http://localhost:4400/vendors~main.iframe.bundle.js:13056:21
    at http://localhost:4400/vendors~main.iframe.bundle.js:14944:12
    at http://localhost:4400/vendors~main.iframe.bundle.js:14980:16
    at withGrid (http://localhost:4400/vendors~main.iframe.bundle.js:7271:10)
```

**To Reproduce**
1.  Create new stencil library `nx g @nxext/stencil:lib my-lib`
2. Configure Storybook `nx g @nxext/stencil:storybook-configuration my-lib`
3. Create new component `nx g @nxext/stencil:component my-comp`  
4. Change story file to `my-comp.stories.tsx` 
5. Run storybook `nx storybook my-lib`

**Expected behavior**
Storybook stories should not throw an error when tsx is used.

**Additional context**
It seems to me, there is some additional compilation step with TypeScript, that removes unused imports. When I write something like `h(null)` into the `my-com.stories.tsx` file, it works.

**Comment by DominikPieper** [comment]
That’s correct. That’s why I by default generate a jsx and no tsx file. That’s the solution from the storybook bugtracker. It works without any hacks until the native stencil integration is ready

**Comment by SebastianSchenk** [comment]
Alright, thanks for the clarification.
