### ISSUE TITLE
Svelte: dependency on @angular-devkit/schematics

### ISSUE THREAD

**Issue by trumbitta** [nxext/nx-extensions#343]
**Describe the bug**

The application generator (didn't try the other ones) depends on `@angular-devkit/schematics` and it fails if it's not installed.

**To Reproduce**

- Create a empty Nx workspace (this makes it easy on Gitpod: https://github.com/trumbitta/gitpod-nx)
- Install the plugin
- Try to generate a new application

**Expected behavior**

I'd expect the plugin not to depend on `@angular-devkit/schematics` and to be refactored so that it only uses `@nrwl/devkit` and maybe `@nrwl/tao` or some other custom utils.

**Additional context**

I did it for https://github.com/trumbitta/nx-trumbitta/tree/main/packages/nx-plugin-openapi in July (ish).
It's a bit of work but it can be done.
The Nx repo is plenty of code you can look at and even borrow. I got quite a bit of custom utils from there.

**Comment by DominikPieper** [comment]
Yes, that are some old dependencies from post devkit 😅

**Comment by DominikPieper** [comment]
I do some refactorings since a few days, hopefully all Angular devkit dependencies are away after that

**Comment by DominikPieper** [comment]
There was an old type from Nx which used @angular-devkit. 13.0.3 should fix this

**Comment by kurtinatlanta** [comment]
The stencil side has the same problem. If i try to run `nx g @nxext/stencil:lib my-lib`, it fails with `Cannot find module '@angular-devkit/schematics'`.
