### ISSUE TITLE
Typescript import from lib fails

### ISSUE THREAD

**Issue by johnwalshuk** [nxext/nx-extensions#345]
**Describe the bug**
I've got a svelte app, and a few svelte libraries that are written in typescript.

I've got a UI library and a DATA library. MY UI library tends to just be `.svelte` files whereas data tends to just be `.ts` files for example my stores, and models.

When i import my ui svelte files (with lang="ts") they import perfectly fine, whereas if I try to import a store i get the following error:
```Error during bundle: Unexpected token (Note that you need plugins to import files that are not JavaScript)```

**To Reproduce**
In a lib create a file called /stores/test.store.ts
```ts
export function test() {}
```
In the index barrel export:
```ts
export * from './stores/test.store';
```

Try and import in main app, and it'll import just fine. Now add a type for example:
```ts
export function test(): void {}
```

**Expected behavior**
To be able to import TS files with typings from a lib

**Additional context**

**Comment by DominikPieper** [comment]
@johnwalshuk Hey, could you try with the new Vite-based builds?

**Comment by johnwalshuk** [comment]
Great that worked, thanks!
