### ISSUE TITLE
Vite: Add project generators for vite

### ISSUE THREAD

**Issue by Jordan-Hall** [nxext/nx-extensions#357]
**Is your feature request related to a problem? Please describe.**
Currently, you can't create standard web projects without any framework. The only solution is to use @nrwl/web which isn't ideal. We should make vite the default build where possible, to replace the need for @nrwl/web in a nxext solution.

@DominikPieper  I was thinking for the first version, I just port over my existing generator for now.  If so I'll make a PR tonight for this. Then I'll take a vite react generator.

**Comment by DominikPieper** [comment]
I think about removing the rollup bundle completely as well. The vite based solution is much easier and faster. Through the vite.config.js the configuration doesn't need any parameter except the vite config itself and I think that's a great solution
