### ISSUE TITLE
Solid: unable to generate application

### ISSUE THREAD

**Issue by Jordan-Hall** [nxext/nx-extensions#370]
**Describe the bug**

Issue when generating solidjs application from

```
Cannot find module '@angular-devkit/schematics'
Require stack:
- C:\dev\cv\node_modules\@nrwl\workspace\src\utils\ast-utils.js
- C:\dev\cv\node_modules\@nrwl\workspace\src\utils\project-type.js
- C:\dev\cv\node_modules\@nrwl\workspace\index.js
- C:\dev\cv\node_modules\@nxext\solid\src\generators\application\lib\add-project.js
- C:\dev\cv\node_modules\@nxext\solid\src\generators\application\application.js
- C:\dev\cv\node_modules\@nrwl\tao\src\shared\workspace.js
- C:\dev\cv\node_modules\@nrwl\cli\lib\init-local.js
- C:\dev\cv\node_modules\@nrwl\cli\bin\nx.js
```

**To Reproduce**

Steps to reproduce the behaviour:

1. npx create-nx-workspace --preset=empty
2. npm install @nxext/solid --save-dev
3. npx nx format
4. npx nx g @nxext/solid:init
5. npx nx g @nxext/solid:app

**Expected behaviour**
Application should generate the app.

**Additional context**
First issue I notice was create-nx-workspace generated version 12. So updated which may have caused this issue (but shouldn't) Cannot find module '@angular-devkit/schematics'

I did found this over on NX issues https://github.com/nrwl/nx/issues/7837

**Comment by Jordan-Hall** [comment]
@kristianmandrup  Are you able to take a look at this issue?

**Comment by DominikPieper** [comment]
This usually means you import something from eg @nrwl/workspace which comes originally from @angular-devkit. ProjectType is ac example here

**Comment by Jordan-Hall** [comment]
> This usually means you import something from eg @nrwl/workspace which comes originally from @angular-devkit. ProjectType is ac example here

Yea it imports workspace. Maybe add it to devpendcey then

**Comment by DominikPieper** [comment]
Unfortunately not all imports from @nrwl/workspace need @angular-devkit. There are just a few, e.g. ProjectType cause that's a reexport from @angular-devkit

**Comment by aldovelasco-acme** [comment]
I'm seeing the same issue with a Stencil based library and an empty Nx preset.

```
// package.json
"@nrwl/cli": "13.3.11",
"@nrwl/jest": "13.3.11",
"@nrwl/tao": "13.3.11",
"@nrwl/workspace": "13.3.11",
"@nxext/stencil": "^13.1.0",
"@stencil/core": "^2.10.0",
"@stencil/sass": "1.5.2",
```

Error when running nx serve [libraryname]
```
Error: Cannot find module '@angular-devkit/schematics'
Require stack:
- project/node_modules/@nrwl/workspace/src/utils/ast-utils.js
- project/node_modules/@nrwl/workspace/src/utils/project-type.js
- project/node_modules/@nrwl/workspace/index.js
- project/node_modules/@nxext/stencil/src/executors/stencil-runtime/prepare-config-and-outputarget-paths.js
- project/node_modules/@nxext/stencil/src/executors/stencil-runtime/index.js
- project/node_modules/@nxext/stencil/src/executors/build/executor.js
- project/node_modules/@nrwl/tao/src/shared/workspace.js
- project/node_modules/@nrwl/tao/src/commands/run.js
- project/node_modules/@nrwl/tao/index.js
- project/node_modules/@nrwl/cli/lib/run-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (project/node_modules/@nrwl/workspace/src/utils/ast-utils.js:11:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by Jordan-Hall** [comment]
> I'm seeing the same issue with a Stencil based library and an empty Nx preset.
> 
> ```
> // package.json
> "@nrwl/cli": "13.3.11",
> "@nrwl/jest": "13.3.11",
> "@nrwl/tao": "13.3.11",
> "@nrwl/workspace": "13.3.11",
> "@nxext/stencil": "^13.1.0",
> "@stencil/core": "^2.10.0",
> "@stencil/sass": "1.5.2",
> ```
> 
> Error when running nx serve [libraryname]
> 
> ```
> Error: Cannot find module '@angular-devkit/schematics'
> Require stack:
> - project/node_modules/@nrwl/workspace/src/utils/ast-utils.js
> - project/node_modules/@nrwl/workspace/src/utils/project-type.js
> - project/node_modules/@nrwl/workspace/index.js
> - project/node_modules/@nxext/stencil/src/executors/stencil-runtime/prepare-config-and-outputarget-paths.js
> - project/node_modules/@nxext/stencil/src/executors/stencil-runtime/index.js
> - project/node_modules/@nxext/stencil/src/executors/build/executor.js
> - project/node_modules/@nrwl/tao/src/shared/workspace.js
> - project/node_modules/@nrwl/tao/src/commands/run.js
> - project/node_modules/@nrwl/tao/index.js
> - project/node_modules/@nrwl/cli/lib/run-cli.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (project/node_modules/@nrwl/workspace/src/utils/ast-utils.js:11:22)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
> ```

Will work on a fix when I'm back feeling well. For now add it as a dev dependency and it will work fine

**Comment by DominikPieper** [comment]
@Jordan-Hall  should be already fixed and will be rolled out with the next release

**Comment by yamiteru** [comment]
@DominikPieper Can you release the new version already?

**Comment by DominikPieper** [comment]
@yamiteru did it right now
