### ISSUE TITLE
Stencil: adding output target fails with error 'Required property importPath is missing'

### ISSUE THREAD

**Issue by bigfish** [nxext/nx-extensions#377]
**Describe the bug**
'@nxext/stencil:add-outputtarget mylib' fails with error

 >: nx g @nxext/stencil:add-outputtarget web-components
✔ Which framework do you use? · react
Please use a buildable library for custom outputtargets

You could make this library buildable with:

nx generate @nxext/stencil:make-lib-buildable web-components
or
ng generate @nxext/stencil:make-lib-buildable web-components

 >: nx generate @nxext/stencil:make-lib-buildable web-components
✔ Which stylesheet format would you like to use? · css
Required property 'importPath' is missing

**Expected behavior**
it adds react output target to the previously created stencil library

**Additional context**
latest nx 13.3.1
had just created a stencil library project named 'web-components', and generated a single component.

**Comment by DominikPieper** [comment]
@bigfish Good morning, seems like the printed example needs to get an addition. What's failing here is what the message says. For Buildable libs you need to set the importPath. so just add --importPath='@myws/web-components' or whatever the path should be

**Comment by eglove** [comment]
Thank you @DominikPieper to be clear, the following command works:

`nx g @nxext/stencil:make-lib-buildable --importPath='@companyName/web-components`
