### ISSUE TITLE
Svelte: external module error when building

### ISSUE THREAD

**Issue by OneWinged-Eagle** [nxext/nx-extensions#387]
**Describe the bug**
When I serve/build my Svelte web application, I get a rollup error like so `No name was provided for external module 'svelte' in output.globals – guessing 'svelte'`.
I was using Axios and got the same error (`No name was provided for external module 'axios' in output.globals – guessing 'axios'`) but I replaced it with the basic fetch.

**To Reproduce**
After installing the nxext/svelte, I did some tweaking with rollup/ts, mainly a rollup.config.js like so:
```
module.exports = (config) => ({
	...config,

	output: {
		...config.output,
		sourcemap: true
	}
})
```
A sveltePreprocess.config.js like so:
```
module.exports = (options) => {
  const production = options.prod

	return {
		postcss: {
			plugins: [require("tailwindcss"), require("autoprefixer")]
		},
		sourceMap: !production
	}
}
```
A tsconfig.json:
```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "importsNotUsedAsValues": "error",
    "isolatedModules": true,
    "types": ["cypress", "jest", "node", "svelte", "twitch-ext"], // since it overwrite tsconfig.base.json, needs to copy-paste it here (TODO: better solution?)
		"paths": {
			"~/*": ["apps/client/src/*"], // needs to precise the path relative to the tsconfig.base.json
			// since it overwrite tsconfig.base.json, needs to copy-paste it here (TODO: better solution?)
			"@myproject/db-typings": ["libs/db-typings/src/index.ts"]
		}
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

For it to work, I did a weird hack in "@nxext\svelte\src\executors\build\builder.js", line 18, by removing "svelte" from the dependencies like so:
```
const dependencies = (0, buildable_libs_utils_1.calculateProjectDependencies)(projGraph, context.root, context.projectName, context.targetName, context.configurationName).dependencies.filter(({ name }) => name !== "svelte");
```

**Expected behavior**
Well, to simply have it working without doing the weird dependencies hack. :p
Maybe I did some crazy shit with my config and that's the cause of the problem?

**Additional context**
Probably not related, but I couldn't make the .env / .env.local with the `process.env.ENV_VAR` to work either.

**Comment by DominikPieper** [comment]
@OneWinged-Eagle the new vite based version is deployed
