### ISSUE TITLE
Jest unit test doesn't find spec.tsx files

### ISSUE THREAD

**Issue by guisperandio** [nxext/nx-extensions#40]
After setting up the stenciljs plugin I tried to run the test using `nx test my-lib` but the result was that:

![image](https://user-images.githubusercontent.com/29610284/87035624-81573580-c1e1-11ea-8887-0ca014c1544d.png)

**Comment by DominikPieper** [comment]
Hi, could you try out version 1.0.1? It should fix it

**Comment by guisperandio** [comment]
It worked perfectly. Thanks @DominikPieper :)
