### ISSUE TITLE
Svelte: files in the public directory are served at the root path

### ISSUE THREAD

**Issue by oscar-marion** [nxext/nx-extensions#404]
**Describe the bug**
The default index.html template uses the `/public/global.css` and `/public/favicon.ico` paths to link respectively the app css and favicon. When serving the app, we get the following warning in the CLI:

```
files in the public directory are served at the root path.
Instead of /public/global.css, use /global.css.
files in the public directory are served at the root path.
Instead of /public/favicon.ico, use /favicon.ico.
```

**To Reproduce**

1. `npm i -D @nxext/svelte --legacy-peer-deps`
2. `nx g @nxext/svelte:app svelte-app`

**Expected behavior**
No warning about static files.

**Comment by Jordan-Hall** [comment]
Thank you for the contribution :)
