### ISSUE TITLE
Stencil: Build fails, (0 , workspace_1.readJsonFile) is not a function

### ISSUE THREAD

**Issue by eglove** [nxext/nx-extensions#405]
**Describe the bug**
I can not build a Stencil library immediately after creating it. It fails with the following error:

```
> nx run web-components:build --verbose
(0 , workspace_1.readJsonFile) is not a function
TypeError: (0 , workspace_1.readJsonFile) is not a function
    at copyOrCreatePackageJson (C:\Users\eglove\Projects\ethan-gone\node_modules\.pnpm\@nxext+stencil@13.1.0_c85b6e2e4017c9570146ef9fc4663e52\node_modules\@nxext\stencil\src\executors\stencil-runtime\prepare-config-and-outputarget-paths.js:27:58)
    at prepareDistDirAndPkgJson (C:\Users\eglove\Projects\ethan-gone\node_modules\.pnpm\@nxext+stencil@13.1.0_c85b6e2e4017c9570146ef9fc4663e52\node_modules\@nxext\stencil\src\executors\stencil-runtime\prepare-config-and-outputarget-paths.js:63:5)
    at C:\Users\eglove\Projects\ethan-gone\node_modules\.pnpm\@nxext+stencil@13.1.0_c85b6e2e4017c9570146ef9fc4663e52\node_modules\@nxext\stencil\src\executors\stencil-runtime\prepare-config-and-outputarget-paths.js:67:9
    at Generator.next (<anonymous>)
    at C:\Users\eglove\Projects\ethan-gone\node_modules\.pnpm\tslib@2.3.1\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\eglove\Projects\ethan-gone\node_modules\.pnpm\tslib@2.3.1\node_modules\tslib\tslib.js:113:16)
    at prepareConfigAndOutputargetPaths (C:\Users\eglove\Projects\ethan-gone\node_modules\.pnpm\@nxext+stencil@13.1.0_c85b6e2e4017c9570146ef9fc4663e52\node_modules\@nxext\stencil\src\executors\stencil-runtime\prepare-config-and-outputarget-paths.js:66:34)
    at C:\Users\eglove\Projects\ethan-gone\node_modules\.pnpm\@nxext+stencil@13.1.0_c85b6e2e4017c9570146ef9fc4663e52\node_modules\@nxext\stencil\src\executors\build\executor.js:37:92
    at Generator.next (<anonymous>)

———————————————————————————————————————————————

>  NX   ERROR  Running target "web-components:build" failed

  Failed tasks:

  - web-components:build
  ```

**To Reproduce**

`nx g @nxext/stencil:library web-components`

`nx g @nxext/stencil:make-lib-buildable --importPath='@companyName/web-components' web-components`

**Expected behavior**

Build files are generated in dist/packages/web-components of Nx repo.

**Additional context**

@nrwl versions: 13.4.1
@nxext/stencil: 13.1.0
@stencil/core: 2.12.0

This is on a fresh build, no changes to default configs.

**Comment by DominikPieper** [comment]
@eglove hi, thanks for the issue. Looks like with Nx 13.4 the function was removed 😅 I’ll take a look the next days

**Comment by eglove** [comment]
Ok, yes, there are a lot of changes between 13.4 and 13.3 unfortunately. The directory structure of generation even changes.

I have another project running on 13.3.6, I'll see if I can move this one to that.

**Comment by eglove** [comment]
@DominikPieper I moved @nrwl/workspace back to 13.3.12 to get past this issue. However, there still seems to be a misconfiguration between Rollup and TypeScript when running the build on the dev server.

```
Rollup: Parse Error
Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
```

```
@Component({
  shadow: true,
```

I tried using @rollup/plugin-typescript and adding this to stencil.config.ts

```
rollupPlugins: {
  before: [typescript()],
},
```

No luck. Is there another workaround for this?

**Comment by pranav-js** [comment]
is there any way to fix this on latest nx? I just migrated angular project to nx fresh and now added stencil library :(, don't want to downgrade.

**Comment by DominikPieper** [comment]
@pranav-js not that easy unfortunately. The error just came up with the latest version two days ago and I don’t make it until after Christmas to fix it

**Comment by pranav-js** [comment]
@DominikPieper no worries. for now downgraded workspace package only. enjoy ur xmas holidays :)
