### ISSUE TITLE
React: Unable to resolve @nxext/react:app

### ISSUE THREAD

**Issue by LoriKarikari** [nxext/nx-extensions#415]
**Describe the bug**
When I try to create a new React app or library, I am getting the following error:
```
Unable to resolve @nxext/react:app
Cannot find module '/home/lori/nx-test/node_modules/@nxext/react/generators.json'
```

**To Reproduce**
I followed the installation steps from the [docs](https://nxext.dev/docs/react/installation) with NX version `13.4.2`:

```
npx create-nx-workspace --preset=empty
```

```
npm install @nxext/react --save
```

```
npx nx g @nxext/react:app [name]
```

**Expected behavior**
A new React library or app is created.

**Comment by eglove** [comment]
Nxext doesn't have a React extension, nor is it needed. Try the official @nrwl/react.

**Comment by LoriKarikari** [comment]
@eglove according to the [Nxext docs](https://nxext.dev/docs/react/overview)  they provide a React with Vite alternative to the official extension. I am already using the official one and want to switch from Webpack to Vite.

**Comment by Jordan-Hall** [comment]
> Nxext doesn't have a React extension, nor is it needed. Try the official @nrwl/react.
> 
> https://nx.dev/l/r/react/overview

We do have React plugin, as Nxext is the vite drop in replacement to Nrwl NX.  Nrwl is based on webpack as we aim to be vite base.

**Comment by Jordan-Hall** [comment]
@LoriKarikari  I'll take a look tonight at why this has stopped working. NX done some structural change and I've recently matched the changes. Seems like something gone wrong with this plugin

**Comment by LoriKarikari** [comment]
@Jordan-Hall tyvm!

**Comment by Jordan-Hall** [comment]
@DominikPieper looks like its just not being included in the bundle :/ can you fix this as part of the CI

**Comment by DominikPieper** [comment]
Could you all test the latest release? Should be fixed now :-)

**Comment by LoriKarikari** [comment]
@DominikPieper it works now! Ty 😊
