### ISSUE TITLE
<Stencil>: Build of new project fails

### ISSUE THREAD

**Issue by jiriKralovec** [nxext/nx-extensions#417]
**Describe the bug**
When running a build on fresh Stencil project, the build fails with this error:

```
> nx run mobile-app:build --verbose
(0 , fileutils_1.writeJsonFile) is not a function
TypeError: (0 , fileutils_1.writeJsonFile) is not a function
    at copyOrCreatePackageJson (C:\Users\istil\Projects\nx-stencil\node_modules\@nxext\stencil\src\executors\stencil-runtime\prepare-config-and-outputarget-paths.js:42:39)
    at prepareDistDirAndPkgJson (C:\Users\istil\Projects\nx-stencil\node_modules\@nxext\stencil\src\executors\stencil-runtime\prepare-config-and-outputarget-paths.js:63:5)
    at C:\Users\istil\Projects\nx-stencil\node_modules\@nxext\stencil\src\executors\stencil-runtime\prepare-config-and-outputarget-paths.js:67:9
    at Generator.next (<anonymous>)
    at C:\Users\istil\Projects\nx-stencil\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\istil\Projects\nx-stencil\node_modules\tslib\tslib.js:113:16)
    at prepareConfigAndOutputargetPaths (C:\Users\istil\Projects\nx-stencil\node_modules\@nxext\stencil\src\executors\stencil-runtime\prepare-config-and-outputarget-paths.js:66:34)
    at C:\Users\istil\Projects\nx-stencil\node_modules\@nxext\stencil\src\executors\build\executor.js:37:92
    at Generator.next (<anonymous>)

———————————————————————————————————————————————

>  NX   ERROR  Running target "mobile-app:build" failed

  Failed tasks:

  - mobile-app:build

  Hint: run the command with --verbose for more details.
```

`nx report` output:

```
 NX  Report complete - copy this into the issue template

  Node : 16.13.1
  OS   : win32 x64
  npm  : 8.3.0

  nx : 13.4.3
  @nrwl/angular : 13.4.3
  @nrwl/cli : 13.4.3
  @nrwl/cypress : 13.4.3
  @nrwl/devkit : 13.4.3
  @nrwl/eslint-plugin-nx : 13.4.3
  @nrwl/express : 13.4.3
  @nrwl/jest : 13.4.3
  @nrwl/linter : 13.4.3
  @nrwl/nest : 13.4.3
  @nrwl/next : undefined
  @nrwl/node : 13.4.3
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.3
  @nrwl/web : 13.4.3
  @nrwl/workspace : 13.4.3
  @nrwl/storybook : 13.4.3
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @nxext/stencil: 13.1.0

(node:9152) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\istil\Projects\nx-stencil\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**To Reproduce**
1. Create new NX workspace using `npx create-nx-workspace {{name}}`
2. Create new Stencil project using `nx g @nxext/stencil:app mobile-app --style=scss`
3. Run build using `nx build {{name}} --verbose`

**Expected behavior**
It is expected that the build finishes without issues.

**Additional context**
Node versions:
- 16.13.1 with npm@8.3.0
- 14.18.1 with npm@6.14.15

**Comment by DominikPieper** [comment]
Could you add the output of: nx report?

**Comment by jiriKralovec** [comment]
> Could you add the output of: nx report?

Added

**Comment by eglove** [comment]
I updated to @nxext/stencil^13.1.1 last night, it's working and building fine with 13.4.2.

I haven't readded back the extension of tsconfig.base.json [as I mentioned here](https://github.com/nxext/nx-extensions/issues/405#issuecomment-1000949864). But that was a different issue.

**Comment by DominikPieper** [comment]
@eglove usually the peer dependencies show what version is needed. For @nxext/stencil 13.1.x it's Nx 13.4.x. Unfortunately, they moved e.g. writeJsonFile. After that, it won't work anymore at needs to be changed. ^^'

**Comment by DominikPieper** [comment]
@jiriKralovec did you use the latest version of @nxext/stencil? 13.1.x should work with Nx 13.4. They did some breaking changes

**Comment by jiriKralovec** [comment]
@DominikPieper The latest patch version `13.1.2` seems to be working with Nx `13.4.3`. Thanks for swift response!

**Comment by eglove** [comment]
> @eglove usually the peer dependencies show what version is needed. For @nxext/stencil 13.1.x it's Nx 13.4.x. Unfortunately, they moved e.g. writeJsonFile. After that, it won't work anymore at needs to be changed. ^^'

Peer dependencies that can be taken seriously? Ha

It is specifically nxext/stencil 13.1.0 that has an issue with nrwl/workspace 13.4.x. Recent updates have fixed it.

**Comment by DominikPieper** [comment]
@eglove It's hard to find a versioning schema that covers the Nx compatibility and own changes ^^' even more since there are breaking changes in Nx minor versions.
