### ISSUE TITLE
Stencil 1.16.2 - Job Output failed to validate.

### ISSUE THREAD

**Issue by Rick313** [nxext/nx-extensions#43]
[Nx Workspace]
- @nrwl/**: 9.5.1
- typescript: 3.9.6

[Screenshot]
![Capture](https://user-images.githubusercontent.com/29020561/87224237-efd3f900-c383-11ea-8217-32e33c624ba8.PNG)

**Comment by DominikPieper** [comment]
Hi, the error is known. The plugin don't work with 1.16 up, see #35 
The stencil compiler api changed and I talk already to Adam what need to be re-added

**Comment by DominikPieper** [comment]
There's Version 1.1.0 which uses 1.16.3
