### ISSUE TITLE
Stencil: Angular output target not including components

### ISSUE THREAD

**Issue by deprecat3d** [nxext/nx-extensions#431]
**Describe the bug**
I created a default stencil library and add angular output target. When I serve my stencil library a generated folder is created in folder of output target. I think that's expected but this generated folder not contain my component in <libname>-angular.module.ts provided. These components are in proxies.ts file. Is this the expected behavior? How can i render this components?

**To Reproduce**
My ui-kit created with stencil 
![image](https://user-images.githubusercontent.com/53632252/149717001-843fa39a-04ac-4a08-8d84-a5413ec27ba2.png)

my ui-kit stencil.config.ts
![nx-issue1](https://user-images.githubusercontent.com/53632252/149717276-96e7174e-1871-4280-8b4a-a9d73d1143f6.png)

the output target
![image](https://user-images.githubusercontent.com/53632252/149717490-c88ba3b2-71df-4285-b505-22406662d688.png)

my tsconfig.base.json
![nx-issue2](https://user-images.githubusercontent.com/53632252/149717615-b6d47fc7-74a0-4d50-a976-c3eccb99632f.png)

my microfrontend trying to consume ui-kit-angular
![nx-issue3](https://user-images.githubusercontent.com/53632252/149718226-d6e092d1-675d-4726-8970-c047de54a842.png)

`<my-component></my-component>
<router-outlet></router-outlet>
`

This render nothing. No console errors

**Expected behavior**
I expect that provided ui-kit-angular.module.ts includes my components.

**Comment by DominikPieper** [comment]
Yes, that's the default here. The component generation is handled by the stencil outputarget and I create the empty Angular library for easier setup. Unfortunately, you've to add and export the generated Components into the library module yourself.
Like e.g. here https://github.com/nxext/nxext-demo/blob/main/libs/core-angular/src/lib/core-angular.module.ts

**Comment by deprecat3d** [comment]
Thank you @DominikPieper. Components now rendering as well. 
I closed this issue but if you could help me one more time: the style of component not be applied in microfrontend. Any reason? I missed something?
