### ISSUE TITLE
Has vue support removed?

### ISSUE THREAD

**Issue by codef0rmerz** [nxext/nx-extensions#435]
I can see [the output type to be vue](https://nxext.dev/docs/stencil/generators/add-outputtarget) while running`add-outputtarget` command but it throws `Property 'outputType' does not match the schema. 'vue' should be one of angular,react.`

```
nx g @nxext/stencil:add-outputtarget core  --importPath=@design-system/core-vue --publishable --outputType='vue'
```

Is it possible?

P.S.:
@nxext/stencil: "^13.1.2
@stencil/vue-output-target: "^0.6.0"

**Comment by DominikPieper** [comment]
I removed the vue support temporarily because the nx vue plugin wasn’t able to run wir latest Nx

**Comment by codef0rmerz** [comment]
For me the vue app is not getting generated with Nx 13 but I managed to generate a StecilJS proxy for Vue by adding following to `stencil.config.js`

```
import { vueOutputTarget } from '@stencil/vue-output-target';

export const config: Config = {
  namespace: 'core',
  taskQueue: 'async',
  plugins: [sass()],
  outputTargets: [
    vueOutputTarget({
      componentCorePackage: '@design-system/core',
      proxiesFile: '../../../libs/core-vue/src/generated/components.ts',
    })
  ]
}
```

So the only problem is that I can not use this proxied component in a Vue app in the same workspace. I'll have to create a Vue app separately to test it.

**Comment by DominikPieper** [comment]
Did the vue plugin works for you? I tried it lately and wasn’t able to use it with latest Nx

**Comment by codef0rmerz** [comment]
@DominikPieper Nope, could not create vue-app but vue proxy components are getting generated with above output target.
