### ISSUE TITLE
Failed to resolve entry for package error

### ISSUE THREAD

**Issue by EliRobinson** [nxext/nx-extensions#445]
### Discussed in https://github.com/nxext/nx-extensions/discussions/440

<div type='discussions-op-text'>

<sup>Originally posted by **EliRobinson** January 25, 2022</sup>
I'm running into a weird issue.

I get this error when I run build on one of my libs.

```[vite:resolve] Failed to resolve entry for package "@arrived/common". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@arrived/common". The package may have incorrect main/module/exports specified in its package.json.```

My setup is as follows:
I have 4 libs: Api, Common, Images, and Components.

This is my dependency graph.
![image](https://user-images.githubusercontent.com/7842911/151118867-e7a6d588-6fa9-4fac-af5f-2b85db2d6fc2.png)

I can build common fine.
I can build api (and in turn common) fine.
I can build images fine.
As soon as I try to build components though, I get this error. Googling the error has returned nothing.

Is there some config I'm missing?

Within reason I can share my config (it's proprietary so I can't share everything), but I'm just flabbergasted...</div>

**Comment by DominikPieper** [comment]
Good morning. First question, what plugin are you using? Plain vite? Svelte? React? I’m not able to see that from the error. The vite config could be interesting as well

**Comment by EliRobinson** [comment]
Using this npm package `"@nxext/vite": "^13.1.3",`.

Running this generator: `@nxext/vite:package`

I don't have a vite config for this library. If I'm bundling a bunch of react components, do I need to use a specialized react version of the above generator?

For reference, it's hitting this piece of code and throwing the exception:
https://github.com/vitejs/vite/blob/fb7ba5353bb35d41f2ec2c90b6b8e5fecd508d07/packages/vite/src/node/plugins/resolve.ts#L761

**Comment by EliRobinson** [comment]
My goal is to create 4 different bundled libs (some consume each other) so they can be used a standalone imports for 3 different apps. A React CRA app, a React Native app, and a NextJS app. I'm breaking sharable code into these bundled libs.

**Comment by DominikPieper** [comment]
@EliRobinson for React we have @nxext/react. It does that, creates a react lib or app with a vite config. For React Vite needs the react vite plugin. You could create a config yourself and use the plugin or use the bundled from our react package. Without any plugins Vite isn't capable to process React

**Comment by EliRobinson** [comment]
Ok, @DominikPieper - I'll try creating a generated test-lib and see what the config looks like and how it differs from what I've got. I'll post my findings here.

**Comment by EliRobinson** [comment]
Ok that seems to have to worked!! I can't tell you how much time is wasted only to try your recommendation and 15 min later it's magic... You are a wizard...

Here's the main differences for reference:
```
tsConfig

"lib": ["DOM", "DOM.Iterable", "ESNext"],
"allowJs": true,
"skipLibCheck": false,
"allowSyntheticDefaultImports": true,
"forceConsistentCasingInFileNames": true,
"jsx": "react-jsx",
"types": ["vite/client", "@nxext/react/client"]
"isolatedModules": true,

instead of

"lib": ["ESNext", "DOM"],
"sourceMap": true,
"noUnusedLocals": true,
"noUnusedParameters": true,
"noImplicitReturns": true
```

```
project.json

"configFile": "@nxext/vite/plugins/vite-package",
"frameworkConfigFile": "@nxext/react/plugins/vite",

instead of

"packageJson": "package.json",
"assets": ["assets"],
"viteConfig": "@nxext/vite/plugins/vite-package"
```

instead of
