### ISSUE TITLE
Svelte: Can't create app with cypress as e2eTestRunner

### ISSUE THREAD

**Issue by Lcarv20** [nxext/nx-extensions#452]
**Describe the bug:**
Creating svelte app is not working if I have cypress as e2eTestRunner.
**To Reproduce:**
`
npm I @nxext/svelte
nx generate @nxext/svelte:application
`
<img width="1012" alt="Screenshot 2022-02-05 at 02 18 23" src="https://user-images.githubusercontent.com/42584819/152623307-9419c8ea-d8ee-44ce-9663-3a64090d5b92.png">
**Expected behavior**
It would be expected to create the app but it's not, only if the `e2eTestRunner` option is set to `none`

**Additional context**
I have used this not so long ago, I noticed you have made some changes, however couldn't yet find the bug. If I find I will post further.

**Comment by DominikPieper** [comment]
Hey, yea sorry the next release will fix it. The function signature changed with 13.7

**Comment by DominikPieper** [comment]
Should be fixed with the latest release
