### ISSUE TITLE
Angular: Can't take an interface as @Input to a component

### ISSUE THREAD

**Issue by fatihdogmus** [nxext/nx-extensions#489]
**Describe the bug**
When you take an interface as input to a component, it doesn't load the application and gives the following error: "Uncaught SyntaxError: The requested module '/src/app/File.ts' does not provide an export named 'InterfaceName'
I've not created the project with the generator, but instead, added it to an existing application, since this is our use case for our real application.

**To Reproduce**
Here is a repo to reproduce the issue: https://github.com/fatihdogmus/angular-vite-demo

Problem is on app.component.ts. When you remove the @Input annotation from item, it compiles successfully.
**Expected behavior**
It should compile without errors.
**Additional context**
Also there are bunch of errors concerning missing source maps, but I don't know if this is relavent:
![image](https://user-images.githubusercontent.com/16986743/154329479-0102ecce-9db5-48df-99a3-c3a6bc667654.png)

**Comment by Jordan-Hall** [comment]
Hey @fatihdogmus this is strange. Taking a look now now to see how it should be handled. It looks like an issue at SWC layer but need to keep checking

**Comment by Jordan-Hall** [comment]
Bug filed with SWC to see what the best solution will be. Maybe we do what I was thinking all along and transfer interfaces in classes and throw a not implemented error. That way we could in theory use angular DI with interfaces.

https://github.com/swc-project/swc/issues/3601

**Comment by fatihdogmus** [comment]
OK than you very much jordan. I will keep tinkering on project and see if i can get it working with our project after the issue is resolved.

**Comment by Jordan-Hall** [comment]
@fatihdogmus  the next version does have a work around. But you can do it now, if you upgrade @swc/core pacakage to the lastest. The use `import type {} ....` intead of `import {} ...` then it should work.
