### ISSUE TITLE
<Vite>: generator uses wrong config parameter for Vite config file

### ISSUE THREAD

**Issue by realityfilter** [nxext/nx-extensions#497]
**Describe the bug**
The generator uses 'viteConfig' as configuration param instead of 'configFile'

See:
https://github.com/nxext/nx-extensions/blob/ca82905e2fddb0072dedff5757bb7ed983da8bae/packages/vite/src/generators/library/library.ts#L148

** Reproduce

nx g @nxext/vite:library testlib --buildable=true

Look at workspace.json it uses the wrong config param for vite.config

**Expected behavior**

The generator uses the correct config param.

**Comment by Jordan-Hall** [comment]
I'll make the changes tonight. We orignay had 3 config one being the base.

**Comment by Jordan-Hall** [comment]
@realityfilter this fixed on next release. Added a migration script to fix the issue too
