### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by rewathkafley** [nxext/nx-extensions#50]
This error pops up when i run the project:
![image](https://user-images.githubusercontent.com/9987781/88137058-8cac5700-cc0c-11ea-8cdc-f6f15f934bfd.png)

**Comment by DominikPieper** [comment]
Which version of the plugin and which stencil version did you use?

**Comment by rewathkafley** [comment]
> Which version of the plugin and which stencil version did you use?
Hi @DominikPieper  I am using the following version of stencil and plugin

 **"@nxext/stencil": "^1.1.0",
"@stencil/core": "1.16.3"**

**Comment by DominikPieper** [comment]
Okay, one question that came up. Nx 10? Until now there's no nx 10 support
