### ISSUE TITLE
Svelte: generator error - puts everything in packages

### ISSUE THREAD

**Issue by swallace21** [nxext/nx-extensions#515]
nx g @nxext/svelte:app my-app

Running the above command creates everything under packages.

Instead of apps

Thanks!

**Comment by swallace21** [comment]
I needed to create an nx workspace that supports apps first. ;)

npx create-nx-workspace --preset=empty

**Comment by DominikPieper** [comment]
A good place to look here is the nx.json. You're able to configure the workspaceLayout there:

```
  "workspaceLayout": {
    "appsDir": "e2e",
    "libsDir": "packages"
  },
```
