### ISSUE TITLE
Vite: libs in nx repo does not work with vite

### ISSUE THREAD

**Issue by VincentThomas06** [nxext/nx-extensions#519]
**Describe the bug**
when i try to import a library in the nx repo (from `/libs` dir) it says the file does not exist. I imported it with compilerOptions.paths but i've also tried normal import

**To Reproduce**

* create a nx monorepo with `create-nx-workspace`
* create a vite react app with this plugin
* create a react library with the standart `@nrwl/react` command
* import it to the vite app

**Expected behavior**

That the lib does import and will work as expected

**Comment by Jordan-Hall** [comment]
Can you put together a demo repo. I'll take a look at it.

**Comment by VincentThomas06** [comment]
I'll be able to do it in a few hours...

**Comment by VincentThomas06** [comment]
> Can you put together a demo repo. I'll take a look at it.

Here: https://github.com/VincentThomas06/issue-nxextensions

**Comment by Jordan-Hall** [comment]
Hey @VincentThomas06  you are using ["nx-plugin-vite"](https://github.com/LinbuduLab/nx-plugins) which isn't our plugin. If you want to use ours it's @nxext/react/ .

If you need anymore help. I'm happy to help you.

**Comment by VincentThomas06** [comment]
> Hey @VincentThomas06  you are using ["nx-plugin-vite"](https://github.com/LinbuduLab/nx-plugins) which isn't our plugin. If you want to use ours it's @nxext/react/ .
> 
> If you need anymore help. I'm happy to help you.

Im so sorry opened an issue on the wrong repo 😂

**Comment by Jordan-Hall** [comment]
No problem.  Happy to help send you the config you need for this one if you need it. It fully support nx libs
