### ISSUE TITLE
Unable to install stencil lib

### ISSUE THREAD

**Issue by MMT-LD** [nxext/nx-extensions#56]
Hey, 

When installing a fresh nx project, which is using the latest versions of everything. Most things work, however, running ```nx g @nxext/stencil:lib my-lib``` results in an error ```cannot read property 'paths' of undefined```. All other libs work, i.e. ```nx generate @nrwl/react:library``` it just seems to be this package. Any ideas?

Thanks in advance

EDIT: Looks like latest version is not supported yet. Sorry my mistake.

**Comment by DominikPieper** [comment]
Hey, yes nx 10 isn't working yet. There are some changes (mostly with tsconfig) but I'll push a working version for nx 10 within the next days

**Comment by DominikPieper** [comment]
Hay, you could try the preview version  @nxext/stencil@10.0.0-0

**Comment by MMT-LD** [comment]
@DominikPieper Thanks ill give it a try
