### ISSUE TITLE
Vite | React: UI Library Build Fails

### ISSUE THREAD

**Issue by mwarger** [nxext/nx-extensions#632]
**Describe the bug**
After creating a default @nxext/react:library, the build command fails.

```
> nx run sample-ui-lib:build

vite v2.9.5 building for production...
✓ 1 modules transformed.
Generated an empty chunk: "index"
../../dist/libs/sample-ui-lib/sample-ui-lib.es.js   0.00 KiB / gzip: 0.02 KiB
Generated an empty chunk: "index"
../../dist/libs/sample-ui-lib/sample-ui-lib.umd.js   0.09 KiB / gzip: 0.09 KiB
(0 , assets_1.copyAssets) is not a function
```

**To Reproduce**
Follow the installation instructions here:
https://nxext.dev/docs/react/installation.html

Create a new buildable library with that plugin.  

Run the build command.

**Expected behavior**
I would expect the build to succeed without any errors.

**Additional context**
It appears the build output actually writes to the appropriate dist folder, but the build still fails.

nx --version
13.10.3

**Comment by DominikPieper** [comment]
Hey, could you add the output of `nx report` please?

**Comment by mwarger** [comment]
@DominikPieper Here you are.

Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx : 13.10.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.2
   @nrwl/eslint-plugin-nx : 13.10.3
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.3
   @nrwl/js : 13.10.3
   @nrwl/linter : 13.10.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 13.3.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.3
   @nrwl/web : 13.10.3
   @nrwl/workspace : 13.10.3
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @nxext/react: 13.0.5

**Comment by Jordan-Hall** [comment]
@DominikPieper i believe this is an issue with vite lib package. I was going to take a look at it this weekend.

**Comment by DominikPieper** [comment]
@Jordan-Hall  from the whole error (see the other one, same with svelte) Nx moved or removed the function in the newest version😅
