### ISSUE TITLE
Stencil: Update peer dependency

### ISSUE THREAD

**Issue by konrad-kinesso** [nxext/nx-extensions#648]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i can't use most recent version of packages.

**Describe the solution you'd like**
Please @DominikPieper can you update [peer dependencies](https://github.com/nxext/nx-extensions/blob/main/packages/stencil/package.json#L31) for stencil package? Thanks :)

**Comment by DominikPieper** [comment]
Hey, I'll update some stuff soon but the peerDependency shouldn't stop you from installing a newer version. Except that there's a warning it should work. That's why I didn't added it as a dependency but a peerDependency

**Comment by kdshop** [comment]
Im sorry, bad phrasing :) It works and it is possible to use the most recent versions i just have to specify `--legacy-peer-deps` while installing dependencies.

**Comment by dgonzalezr** [comment]
@DominikPieper in case it is useful 😉  it happening when upgrading to the latest NX 14.x

![CleanShot 2022-05-02 at 21 16 24](https://user-images.githubusercontent.com/328492/166302523-e78cb432-853e-4956-ae24-e736f935349a.png)

As @kdshop mentioned is working while we add the `--legacy-peer-deps` flag but the ideal would be to work out of the box and resolve all dependencies needed considering the latest nx versions.

**Comment by DominikPieper** [comment]
@dgonzalezr  the nx 14 build isn’t there yet. We’ll release all packages with 14 tomorrow

**Comment by DominikPieper** [comment]
@dgonzalezr and @kdshop V14.0.0 is there and hopefully should fix both :-)
