### ISSUE TITLE
how import a stencil component from a stencil-lib in a stencil-pwa-app

### ISSUE THREAD

**Issue by keremtiryaki** [nxext/nx-extensions#67]
I would like to use a [stencil-lib-component](https://github.com/keremtiryaki/my-stencil-nx-demo/blob/master/libs/stencil-lib/src/components/my-component/my-component.tsx) in [stencil-pwa-app](https://github.com/keremtiryaki/my-stencil-nx-demo/blob/master/apps/stencil-pwa)

for ex:
https://github.com/keremtiryaki/my-stencil-nx-demo/blob/master/apps/stencil-pwa/src/components/app-home/app-home.tsx#L25-L26

is this possible?

**Comment by DominikPieper** [comment]
Hey, sorry for the delay. Yes, it is. You'll have to export the lib component and import the lib or component into your app
