### ISSUE TITLE
Support Stencil 2.0

### ISSUE THREAD

**Issue by b-barry** [nxext/nx-extensions#68]
Hello,

[Stencil 2.0](https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-200-2020-08-31) was released yesterday, I was wondering if this plugin will later support it.

If yes, how could I help to make it happen. I will begin a project in the coming weeks and your plugin will be extremely important for us.

Thanks for this excellent plugin !

**Comment by DominikPieper** [comment]
Hi,
The next update I'll publish will use 2.0 as default. The plugin uses the stencil package available, so there's no direct dependency. The schematic installs version 1 but version 2 comes without breaking changes. I did some tests with the version 2 beta, and it worked, so you can try v2 with just updating the package.json.

Thanks and great that the plugin helps. If you've any problems, let me know.

**Comment by b-barry** [comment]
Super ! @DominikPieper  Thanks for the quick answer. I will try it soon.
