### ISSUE TITLE
Fail to use Stencil output targets

### ISSUE THREAD

**Issue by raisiqueira** [nxext/nx-extensions#70]
Hi, i have a problem with the `nx g @nxext/stencil:add-outputtarget` command. I try to run but after select the output framework the console returns a generic error:

![image](https://user-images.githubusercontent.com/2914170/93205441-33553580-f72e-11ea-8034-58d0b4e9b975.png)

NRWL Workspace version:

```
"@nrwl/workspace": "9.5.1",
"@nxext/stencil": "^1.1.1",
"@stencil/core": "1.16.3",
```

Can someone help me?

**Comment by DominikPieper** [comment]
Hi, something I probably have to add to the docs, for this feature the nx packages @nrwl/angular or @nrwl/react have to be installed for angular and react, cause the schematics will be used.

**Comment by raisiqueira** [comment]
Hi @DominikPieper i have the `@nrwl/angular` at version 9.5.1, but the same error are returned :/

**Comment by raisiqueira** [comment]
Update: I updated my workspace to `nrwl 10` and it worked!
