### ISSUE TITLE
React: Project created with --js=true does not work

### ISSUE THREAD

**Issue by ALMaclaine** [nxext/nx-extensions#731]
**Describe the bug**
React project created with --js=true does not work

**To Reproduce**
Generate application:
`pnpm nx g @nxext/react:application app --js=true"`
`pnpx nx serve`

**Expected behavior**
The app to serve and function correctly.

**Additional context**
The browser console error says cannot find `main.tsx`, this makes sense since `main.tsx` doesn't exist, only `main.js`

When changing index.html to read `main.js`, the terminal console errors out because there is jsx in the main.js but it doesn't have `.jsx` extension.

Changing `main.js` to `main.jsx` makes `app.js` error out for not being `app.jsx`. It appears that `app.js` is generated by `app.tsx` so at this point I'm not sure what to do.

Thanks

**Comment by Jordan-Hall** [comment]
Thank you. I'll take a look at this over the weekend
