### ISSUE TITLE
Angular: Port Firebase executor from nxtend

### ISSUE THREAD

**Issue by dolphinigle** [nxext/nx-extensions#772]
According to [this comment](https://github.com/nxtend-team/nxtend/pull/638#issuecomment-1204196754), [nxtend](https://github.com/nxtend-team/nxtend) is being deprecated in favor of nxext. But Nxext doesn't currently support [firebase](https://github.com/nxtend-team/nxtend/tree/main/packages/firebase), unlike nxtend.

It would be great if Nxext supports firebase too.

If this is within the scope of Nxext, I am happy to contribute by porting this feature with a PR.

**Comment by DominikPieper** [comment]
Hey,
right now we don't plan to migrate @nxtend/firebase to Nxext.

**Comment by WhatsThatItsPat** [comment]
Alternatively, perhaps Nxext would be a good place for a successor to https://github.com/simondotm/nx-firebase
