### ISSUE TITLE
Publishable Vite library/library React - d.ts files and peer dependencies

### ISSUE THREAD

**Issue by jkavalec** [nxext/nx-extensions#812]
This concerns Vite based React and normal libraries, I didn't find any remarks on these so I wanted to ask if it is possible to do currently.
- is there way to generate .d.ts files for typings when building the publishable library?
- is there a way how to have dependencies not bundled in resulting file, but have them as dependencies in package.json?

**Comment by DominikPieper** [comment]
We won't do anything in that direction. I'll close this here cause we'll drop the Support soon in favor of the New @nrwl/vite package and the official @nrwl/react package :-)
