### ISSUE TITLE
Svelte | Vite: Support NX ^15.0.0

### ISSUE THREAD

**Issue by ndrsg** [nxext/nx-extensions#830]
**Is your feature request related to a problem? Please describe.**
I cannot upgrade my NX Workspace to 15.0.5, hence @nxext/svelte produces a dependency conflict.

**Describe the solution you'd like**
Release a @nxext/svelte version on NPM that supports nrwl/nx workspaces >=15
I have seen, there are already commits for NX15, but there is no release yet

**Additional context**
```
npm ERR! Found: @nrwl/linter@15.0.5
npm ERR! node_modules/@nrwl/linter
npm ERR!   dev @nrwl/linter@"15.0.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nrwl/linter@"^14.5.0" from @nxext/svelte@14.0.2
npm ERR! node_modules/@nxext/svelte
npm ERR!   dev @nxext/svelte@"^14.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by DominikPieper** [comment]
The update to nx15 is ongoing right now. After everything runs smoothly, I'll do the release. Sorry about that, but some things need to be fixed first

**Comment by DominikPieper** [comment]
I'll close this. The v15 release is on npm :-)

**Comment by hoi4** [comment]
@DominikPieper Would it be possible to also release updated versions for ionic-angular and capacitor packages?
