### ISSUE TITLE
Capacitor: Npm audit fails,  minimist <1.2.6, severity: critical

### ISSUE THREAD

**Issue by sukhanovr** [nxext/nx-extensions#836]
**Bug description**
Hi!
Apparently, the latest version of `@nxext/capacitor` 15.0.0 depends on vulnerable versions of `minimist` <1.2.6.

**To Reproduce**
1. `npm i @nxext/capacitor`
2. `npm audit`

Outcome:
```
# npm audit report

minimist  <1.2.6
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix --force`
Will install @nxext/capacitor@14.0.0, which is a breaking change
node_modules/minimist
  @nxext/capacitor  >=15.0.0
  Depends on vulnerable versions of minimist
  node_modules/@nxext/capacitor

2 critical severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Expected behavior**
The Npm audit should pass without issues.

**Additional notes**
NX also had it and fixed it in the [15.0.11](https://github.com/nrwl/nx/releases/tag/15.0.11). But since `@nxext/capacitor` requires strict `15.0.10`, I couldn't get their update, so I guess fully get rid of the issue `@nxext/capacitor` should also update it's nx dependencies to `15.0.11`.

**Comment by DominikPieper** [comment]
Hi, das sollte mit dem letzten Update auf 15.2 dann behoben sein.
