### ISSUE TITLE
Vite: package is not published?

### ISSUE THREAD

**Issue by nodegin** [nxext/nx-extensions#837]
**Describe the bug**

The dependencies showing in `packages/vite/package.json` is requiring NX 15+

https://github.com/nxext/nx-extensions/blob/main/packages/vite/package.json

But the actual version installed via NPM is `^14.8.5`

```
{
  "name": "@nxext/vite",
  "version": "14.2.0",
  "license": "MIT",
  "author": "Dominik Pieper",
  "description": "Nx plugin for ViteJs",
  "homepage": "https://nxext.dev/",
  "keywords": [
    "nx",
    "nx-plugin",
    "viteJs",
    "vite"
  ],
  "repository": {
    "type": "github",
    "url": "https://github.com/nxext/nx-extensions"
  },
  "bugs": {
    "url": "https://github.com/nxext/nx-extensions/issues"
  },
  "main": "./src/index.js",
  "typings": "./src/index.d.ts",
  "executors": "./executors.json",
  "generators": "./generators.json",
  "dependencies": {
    "@nrwl/devkit": "14.8.5",
    "rxjs": "^7.0.0",
    "rxjs-for-await": "1.0.0",
    "tsconfig-paths": "^3.14.1",
    "globrex": "^0.1.2"
  },
  "peerDependencies": {
    "@nrwl/workspace": "^14.8.5",
    "vite": "^3.0.5"
  },
  "nx-migrations": {
    "migrations": "./migrations.json"
  },
  "types": "./src/index.d.ts"
}
```

Which causing NPM unable to perform fresh install.

<img width="653" alt="Screen Shot 2022-11-09 at 4 32 15" src="https://user-images.githubusercontent.com/8536244/200657989-6a32b7eb-927f-4990-96c0-757ab81cbf85.png">

**Comment by idealley** [comment]
Same thing here

**Comment by Jordan-Hall** [comment]
Hey, we are removing our vite package in favour of NX vite. Migration will be provided soon

**Comment by ianvieira** [comment]
@Jordan-Hall The stencil package on the repo is also on 15 but on NPM there is no version on this range. Is this expected because of the vite package removal?

**Comment by DominikPieper** [comment]
@ianvieira  this is cause there’s an open issue with the Storybook integration on stencil. Once this is closed the v15 package will be published

**Comment by DominikPieper** [comment]
@ianvieira the new Stencil package is released for v15

**Comment by ianvieira** [comment]
@DominikPieper Thank you very much 🙇🏻

**Comment by DominikPieper** [comment]
I'll close this here :-) We are working on migrations to the new official packages.
