### ISSUE TITLE
Vitest: doesn't resolve typescript aliases

### ISSUE THREAD

**Issue by YonatanKra** [nxext/nx-extensions#852]
**Describe the bug**
I've added nxext/vitest to my existing project and switched one of the libs from `jest` to `vitest`. When I run the tests using `vitest` it doesn't take into account

**To Reproduce**
1. Create a library
2. Create a library that depends on that library by importing using an alias.
3. Run tests using vitest

**Expected behavior**
I'd expect the build to succeed and the files to be taken according to typescript aliases in the `tsconfig.base.json`

**Comment by DominikPieper** [comment]
The Vitest package won't get many updates in the future, cause the ongoing official plugin will replace it

**Comment by YonatanKra** [comment]
Found it: https://nx.dev/packages/vite
Thanks a lot!
