### ISSUE TITLE
Vitest: quits from watchmode without prompt

### ISSUE THREAD

**Issue by YonatanKra** [nxext/nx-extensions#853]
**Describe the bug**
I'm running the tests for a library using `nxext/vitest`. It runs the tests, and then quits.

**To Reproduce**
Just run the tests using `vitest` executor.

**Expected behavior**
I'd expect vitest to remain in watch mode.

**Additional context**
I get the following message from vitest:
```
 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```
But it quits.

**Comment by DominikPieper** [comment]
Hey, we won't do anything in that direction. I'll close this here cause we'll drop the Support soon in favor of the New @nrwl/vite package :-) The package will contain Vitest test features
