### ISSUE TITLE
Nx15 + Ng15 + Nxext + Angular-Ionic@14

### ISSUE THREAD

**Issue by aaronscribner** [nxext/nx-extensions#854]
**Describe the bug**
Cannot npm install with dependency misalignment between angular-ionic and nx15

**To Reproduce**
Create a workspace with nx15
Angular application
Install ionic angular
Create an ionic angular application (https://nxext.dev/docs/ionic-angular/getting-started.html)

**Expected behavior**
Able to build, npm install and run the ionic 6 application utilizing ng15

**Additional context**
npm log files attached
[Archive.zip](https://github.com/nxext/nx-extensions/files/10109016/Archive.zip)

**Comment by aaronscribner** [comment]
Anyone home?

**Comment by DominikPieper** [comment]
The v14 plugin won't work with v15 Nx. We'll release a v15 soon that works with Nx 15

**Comment by DominikPieper** [comment]
Published the new version

**Comment by aaronscribner** [comment]
@DominikPieper 
I will pull the latest and test this week. I will open another bug should I find something more specific.

Thank you for fixing!
