### ISSUE TITLE
Replace nx-project-paths with vite-tsconfig-paths@4

### ISSUE THREAD

**Issue by aleclarson** [nxext/nx-extensions#855]
**Is your feature request related to a problem? Please describe.**
Hi @DominikPieper, I recently reworked `vite-tsconfig-paths` to use Vite's built-in module resolution and I would love for you to try it. It was brought to my attention that Nxext is using a fork of `vite-tsconfig-paths` (called `nx-project-paths`) and I'm curious if there was anything I could do to accommodate your needs in v4 of the plugin, so you don't have to maintain a fork here.

**Describe the solution you'd like**
Using `vite-tsconfig-paths@4` instead of your fork.

If you have any feedback, you can also reach me here: https://discord.com/channels/804011606160703521/1045945939518554122

**Comment by DominikPieper** [comment]
Hey @aleclarson ,
we went with the fork cause we had problems with the tsconfig resolutions that time (months ago)
Right now it should work withe the `vite-tsconfig-paths` package, that's the way the @nrwl/vite package goes. Our Vice package won't get much updates cause we will deprecate it once the official support is ready.

**Comment by aleclarson** [comment]
Cool, thanks for the update!
