### ISSUE TITLE
How to use TailwindCSS wtih @nxext/svelte?

### ISSUE THREAD

**Issue by andrasbacsai** [nxext/nx-extensions#86]
Hey, how can I use TailwindCSS properly with Svelte?
I've tried to use custom `rollup.config.js,` but it does not work.

Always received the following error:

`Error during bundle: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript`)

I think something is with postcss, but not sure.

**Comment by DominikPieper** [comment]
How did you added the rollup configuration? I'm on the feature to extend the internal config right now and I'll add a patch version hopefully later today to add it.

**Comment by andrasbacsai** [comment]
I've just found out that it does not read my custom rollup configuration - I think it did.

I've tried like [this](https://nx.dev/latest/node/plugins/web/builders/package#rollupconfig), but it's a different builder.

**Comment by DominikPieper** [comment]
I published a new version which now is able to add e.g. plugins to the rollup config like the web packages from nrwl does.

Small experiment with tailwind:
```
const postcss = require('rollup-plugin-postcss');
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');

function updateRollup(rollupConfig, options) {

   rollupConfig.plugins = [
    ...rollupConfig.plugins,
    postcss({
      plugins: [
        tailwindcss()
      ]
    })
  ]
  return rollupConfig;
}

module.exports = updateRollup;
```
and
` "rollupConfig": "apps/svelte/update-rollup",`
for the builder options in the workspace.json for build and serve. (tailwind config etc need to be there as well for sure)

**Comment by andrasbacsai** [comment]
It works great, thanks! There is only one thing I need to solve somehow. It is currently bundling the purged CSS into `bundle.js`. It would be better if somehow it can be added to the `bundle.css`, but I could not solve it yet.

**Comment by DominikPieper** [comment]
I'm trying to figure out what would be the best config for this. If I prototyped it I'll add docs about how I did it and maybe add a schematic for it for an easier start

**Comment by DominikPieper** [comment]
@andrasbacsai I added another maybe helpful option to archive that, you're able to hook in a method to configure the svelte preprocessor with something like this:
`function setSveltePreprocessOptions(options) {
  return {
    postcss: {
      plugins: [
        require('postcss-import')(),
        require('postcss-nested')(), // Remove if you can't wan't to use nested structures.
        require('tailwindcss')(options.projectRoot + '/tailwind.config.js'),
      ]
    }
  };
}

module.exports = setSveltePreprocessOptions;
`

**Comment by andrasbacsai** [comment]
Wow, cool. It just works. And as we are adding tailwind into `.svelte`, I can use `@apply` as well. :tada: 

With this configuration, we could use `purge` in development to improve postcss performance `(tailwind.config.js)`:

```
module.exports = {
    future: {
        removeDeprecatedGapUtilities: true,
        purgeLayersByDefault: true
    },
    purge: {
      enabled: true,
      content: ["./apps/**/*.svelte", "./apps/**/*.html"],
      whitelistPatterns: [/svelte-/],
    },
    theme: {
      extend: {},
    },
    variants: {},
    plugins: [],
  } 
```

**Comment by DominikPieper** [comment]
Great. If you've any more problems just let me know. I'll add an example config for tailwind to the docs later I think :-)

**Comment by maku** [comment]
@andrasbacsai Could you explain how to customize the rollup config? I have a "usual" svelte app using rollup and tailwind and want to try using nx. But I cannot find any documentation how to do this.
