### ISSUE TITLE
Documentation references deprecated nxtend docs and contains broken links

### ISSUE THREAD

**Issue by SimonCockx** [nxext/nx-extensions#869]
- [x] The first link in this [contributing section](https://github.com/nxext/nx-extensions/tree/main/packages/ionic-angular#contributing) is broken.
- [x] The Ionic Angular docs also contain links to the deprecated nxtend docs. They should be redirected to <https://nxext.dev/docs/ionic-angular/overview.html>.
- [ ] When submitting a new issue (like this one), the title doesn't suggest starting with "Ionic-Angular", among other plugins that since long have been added. I assume this rule should be brought up-to-date. On the other hand, honestly, since more plugins have been added, I think this approach of placing the relevant package in the issue name will become too verbose. It might be better to just switch to using tags instead, like other repo's do it. (i.e., tags `plugin: angular`, `plugin: svelte`, `plugin: ionic-angular`, etc)
- [x] The main README is out-dated.
- [ ] GitHub "about" is out-dated.
- [ ] On [`npm`](https://www.npmjs.com/package/@nxext/ionic-angular), the repository and homepage confusingly link to `nxtend`.

**Comment by DominikPieper** [comment]
Should be fixed as far as I know

**Comment by SimonCockx** [comment]
@DominikPieper I've updated the checkboxes. There is one left I think.
