### ISSUE TITLE
Ionic-Angular: needs publishing to `npm` for Angular 15 support

### ISSUE THREAD

**Issue by SimonCockx** [nxext/nx-extensions#870]
Since [this commit from October 26](https://github.com/nxext/nx-extensions/commit/5d2193ff853d25b979b73439ca7d9e7bb40fd328#diff-28bc79c93a2d2f024d853e31c3d863a19997d75ff6cfc6eeaa8882100c5655f8), `@nxext/ionic-angular` supports Angular 15. However, the last publish of [`@nxext/ionic-angular`](https://www.npmjs.com/package/@nxext/ionic-angular) on npm was 5 months ago, hence anyone trying to add this package to an Angular 15 project gets in trouble with the message
```
npm ERR! Found: @nrwl/angular@15.3.3
npm ERR! node_modules/@nrwl/angular
npm ERR!   dev @nrwl/angular@"^15.2.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nrwl/angular@"^14.5.0" from @nxext/ionic-angular@14.0.0
npm ERR! node_modules/@nxext/ionic-angular
npm ERR!   dev @nxext/ionic-angular@"14.0.0" from the root project
```

**Comment by SimonCockx** [comment]
@DominikPieper is there any kind of policy on releases? Any plans to release this soon?

**Comment by SimonCockx** [comment]
Great, keep up the good work! I wish you a stressless holiday ^^

**Comment by DominikPieper** [comment]
Pushed the new version
