### ISSUE TITLE
Contributing: `git push` fails with no explanation

### ISSUE THREAD

**Issue by SimonCockx** [nxext/nx-extensions#872]
I have a contribution ready, but I can't push :(

```
nx-extensions> git push
yarn run v1.22.19
$ nx format:check
README.md
packages\ionic-angular\README.md
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-push hook exited with code 1 (error)
error: failed to push some refs to 'https://github.com/SimonCockx/nx-extensions.git'
```

I'm on Windows 11, if that's relevant.

**Comment by SimonCockx** [comment]
Hi @DominikPieper 
It's still failing, unfortunately:
```
nx-extensions> yarn format
yarn run v1.22.19
$ nx format:write
tsconfig.base.json
Done in 1.06s.

nx-extensions> git status
On branch ionic-angular-docs
nothing to commit, working tree clean

nx-extensions> git push
yarn run v1.22.19
$ nx format:check
Done in 0.75s.
husky - pre-push hook exited with code 1 (error)
error: failed to push some refs to 'https://github.com/SimonCockx/nx-extensions.git'
```

**Comment by DominikPieper** [comment]
@SimonCockx mhh strange. These are the commands that get tested with husky:
yarn format:check
yarn documentation
yarn pretty-quick --check

You could disable the lines inside the husky pre-push file and I take a look later

**Comment by SimonCockx** [comment]
@DominikPieper It was my mistake... As a non-unix user I accidentally messed up the shell script.

I present to you: a small contribution to the docs: https://github.com/nxext/nx-extensions/pull/873

**Comment by DominikPieper** [comment]
@SimonCockx great, thank you :-)
