### ISSUE TITLE
Capacitor:   Cannot find module '@nxext/capacitor/package.json'

### ISSUE THREAD

**Issue by sudo-vaibhav** [nxext/nx-extensions#900]
**Describe the bug**
tried to add capacitor using existing react app build output, but some package.json is not resolved.

**To Reproduce**
I have a react app generated using the official nx package. My current nx version is 15.0.7 and I tried installing v13 of the capacitor package.

![image](https://user-images.githubusercontent.com/53619134/217056104-dc53f15c-5d21-42f1-8ab5-f141a77494ce.png)

**Expected behavior**
Generator should be run correctly.

**Additional context**
I think there is some difference between the nx version I am using and the nx version expected by the package, which is older. I had to install nxext capacitor package using --legacy-peer-deps option of npm. Without it, installation wasn't happening.

**Comment by DominikPieper** [comment]
@sudo-vaibhav hey, could you try the latest package I released now?

**Comment by sudo-vaibhav** [comment]
Hi, I tried installing using legacy-peer-deps again and the project generation cli did get going, but gave error at next few steps

https://user-images.githubusercontent.com/53619134/217521531-b37285d2-b173-4180-ae2e-f10a8a1c7dbd.mp4

**Comment by sudo-vaibhav** [comment]
Ok update, I also updated the nx version of my workspace to match the version your latest package was using and it now seems to generate the files and configuration changes needed for capacitor to work. 

I just have a follow up question, the generate command also added a package.json file to the folder of the app. Is that normal? I am not very experienced with nx but with what I have seen so far, nx doesn't create project level package.json, it only has one top-level package.json.

**Comment by DominikPieper** [comment]
The package JSON file is generated cause capacitor needs it, not nx

**Comment by sudo-vaibhav** [comment]
got it, thanks! I will mark this issue as closed.
