### ISSUE TITLE
React/Ionic  NX   (0 , project_configuration_1.shouldDefaultToUsingStandaloneConfigs) is not a function

### ISSUE THREAD

**Issue by seanaguinaga** [nxext/nx-extensions#902]
```
 NX   (0 , project_configuration_1.shouldDefaultToUsingStandaloneConfigs) is not a function
```

![Screenshot_20230216_082959](https://user-images.githubusercontent.com/15254340/219428321-5a3cc318-311b-4324-852d-d7b7ad4b97e0.png)

![Screenshot_20230216_083159](https://user-images.githubusercontent.com/15254340/219428475-1d3812a5-3b33-4ff7-894f-6648f56e8496.png)

**Comment by seanaguinaga** [comment]
It's a 15.7.X thing - 15.6.X and earlier seems to work fine

**Comment by DominikPieper** [comment]
@seanaguinaga 15.7 it’s just released yesterday/today so hadn’t time to test it yet

**Comment by cgrs** [comment]
Same bug in `@nxext/svelte@15.0.1` with `nx@15.7.1`

**Comment by michelm117** [comment]
> Same bug in `@nxext/svelte@15.0.1` with `nx@15.7.1`
Same for `@nxext/ionic-angular`

**Comment by darrenbarklie** [comment]
Also encountered this with the Solid package.

**Comment by spy4x** [comment]
Same for Svelte package

**Comment by tomavic** [comment]
Any updates or clues yet!? 🥲

**Comment by DominikPieper** [comment]
Working on it, faced some issues with the update unfortunately 😅

**Comment by DominikPieper** [comment]
Some packages are updated. Ionic-react and svelte were some of them.

**Comment by DominikPieper** [comment]
@needs wrong repo 😅

**Comment by dcarniel-rebalance** [comment]
@DominikPieper any chance ionic-angular gets updated soon ? I've got the same issue but npmjs.com still only serves 15.6.0 (whereas it has 15.7.0 for ionic-react).

**Comment by DominikPieper** [comment]
@dcarniel-rebalance  working on it but the angular package had an problem updating. I’ll try to update it soon

**Comment by dcarniel-rebalance** [comment]
> @dcarniel-rebalance working on it but the angular package had an problem updating. I’ll try to update it soon

Thanks

**Comment by SimonPrammer** [comment]
Some problem! Thanks for the hard work. Looking forward to a fix.

**Comment by cmddavid** [comment]
@nxext/stencil also has this issue

**Comment by alexdabast** [comment]
> @DominikPieper any chance ionic-angular gets updated soon ? I've got the same issue but npmjs.com still only serves 15.6.0 (whereas it has 15.7.0 for ionic-react).

Did you found a workaround for now ?

**Comment by DominikPieper** [comment]
@alexdabast I released a 15.7 version just now

**Comment by dcarniel-rebalance** [comment]
Thanks @DominikPieper

**Comment by erichstark** [comment]
@DominikPieper did you also published it to npm?
https://www.npmjs.com/package/@nxext/stencil

**Comment by rickbeumers** [comment]
@DominikPieper for me it's available through NPM and confirmed working for @nxext/ionic-angular.

**Comment by DominikPieper** [comment]
@erichstark, yes released a 15.7 compatible here as well

**Comment by crishood** [comment]
Hi, I'm trying to generate a stencil library with 15.7 version but I get this error: NX @nrwl/workspace is not a dependency. Does anyone have the same issue?

**Comment by crishood** [comment]
> Hi, I'm trying to generate a stencil library with 15.7 version but I get this error: NX @nrwl/workspace is not a dependency. Does anyone have the same issue?
I installed @nrwl/workspace and it worked guys.

**Comment by DominikPieper** [comment]
@crishood which kind of workspace do you use? The plugins need an integrated ws

**Comment by vashchukmaksim** [comment]
Is that fixed? I just faced the same error for solid and react apps

nx version: 15.8.5

**Comment by vashchukmaksim** [comment]
Oh, ok got it, thanks!

I downgraded to 15.7.2 but still have the same error (nx --version output is 15.7.2 as well). Am I missing something?

![2023-03-10 15 30 48](https://user-images.githubusercontent.com/26834615/224342037-42bd39b8-2958-4714-8f18-4b006592b652.jpg)

**Comment by DanielMenke** [comment]
The same is happening for https://www.npmjs.com/package/@nxext/sveltekit

package.json:
```json
{
  ....
  "devDependencies": {
    ...
     "@nrwl/cypress": "15.7.2",
    "@nrwl/eslint-plugin-nx": "15.7.2",
    "@nrwl/jest": "15.7.2",
    "@nrwl/js": "15.7.2",
    "@nrwl/linter": "15.7.2",
    "@nrwl/nest": "15.7.2",
    "@nrwl/node": "15.7.2",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/webpack": "15.7.2",
    "@nrwl/workspace": "15.7.2",
    "@nxext/svelte": "^15.7.2.0",
    "@nxext/sveltekit": "^14.0.0-next.2",
    ...
    }
} 
    ```

**Comment by ktrz** [comment]
Hi 
I'm trying to install `@nxext/solid@15.7.0` but it can't find that version on npm. Is this version available publicly?

**Comment by wcontreras** [comment]
Hi
It seems that `@nrwl/web` has the same issue.

Version NX: `15.9.2`

![image](https://user-images.githubusercontent.com/24719927/230412956-d35b3b12-d46c-4275-84c0-df663c065e9e.png)

**Comment by trevordilley** [comment]
I think this is happening for @nrwl/devkit too? All our custom generators break when I migrate tried 15.9.x, 15.8.x, 15.7.x

Seems 15.6.x passes unit tests, going to try our e2e tests now

**Comment by MateraJP** [comment]
I'm new at this, i've run this with --verbose and then checked different versions
![image](https://github.com/nxext/nx-extensions/assets/20309950/d54ab986-313d-4fdf-8d07-ae690be3f078)

The standaloneAsDefault property value seems to be the problem.
the one on the right is @nrwl/js 16.1.4. seems to be a 'work arrownd' been used
![image](https://github.com/nxext/nx-extensions/assets/20309950/565f4a0a-52bb-4236-9c18-68e3bdaaa5d3)

**Comment by tiga05** [comment]
@trevordilley And did it work?

**Comment by DominikPieper** [comment]
There's a latest Version supporting 16.2 now.

**Comment by tiga05** [comment]
Hi Dominik,

thanks for the info. Unfortunately, looks like we can not upgrade due to some dependency issues. I will try to figure it out.
