### ISSUE TITLE
Capacitor: sync requires to install the latest version of @capacitor/cli globally

### ISSUE THREAD

**Issue by mezoistvan** [nxext/nx-extensions#920]
**Describe the bug**
Running `npx nx sync ...` will prompt the user to install the latest version of `@capacitor/cli` globally. 

```
> nx run APPNAME:sync:android

Need to install the following packages:
  @capacitor/cli@4.7.1
Ok to proceed? (y)
```

**To Reproduce**
Make a demo project, add `@capacitor/cli`, `@nxext/capacitor` and try to run an `nx sync...` command.

This is how the relevant part of project.json looks like:

```
    "sync": {
      "executor": "@nxext/capacitor:cap",
      "options": {
        "cmd": "sync"
      },
      "configurations": {
        "ios": {
          "cmd": "sync ios"
        },
        "android": {
          "cmd": "sync android"
        }
      }
    },
```

**Expected behavior**
I expected that the `@capacitor/cli` that is added to the project would be used.
This is important because the latest version of `@capacitor/cli` has a bug and we would not like to use that version during build.

**Additional context**
Installing a particular version of `@capacitor/cli` globally before running `sync` does not work. The `sync` command still wants to install the latest `@capacitor/cli` globally.

**Comment by eggbeard** [comment]
Where is the dependency on `capacitor/cli` even specified?

**Comment by mezoistvan** [comment]
I think this is related to #915 and the dep was defined in #817
