### ISSUE TITLE
React Ionic: Support Ionic 7

### ISSUE THREAD

**Issue by Quraian** [nxext/nx-extensions#923]
Thank you all for providing these awesome extensions for NX. [Now that Ionic 7 is out ](https://ionic.io/blog/ionic-7-is-here) it would be nice if the packages are updated to support it. Also, Vite support addition would be really great if added.

**Comment by muchbetterug** [comment]
Any plans on this?

**Comment by DominikPieper** [comment]
Yes, it's planned. I can't raise a timeline, but hopefully, I'm able to work on this soon

**Comment by DominikPieper** [comment]
@Quraian I released a Ionic 7 version with 16.2

**Comment by Quraian** [comment]
I saw that, thank you Dominik!

**Comment by FranciscoKloganB** [comment]
Sorry for commenting on a closed issue.

Any plans on allowing the project to be created with `vite` and `vitest`? Instead of `webpack` and `jest`?
