### ISSUE TITLE
Stencil : Support for template ref in angular

### ISSUE THREAD

**Issue by OrShalmayev** [nxext/nx-extensions#942]
**Is your feature request related to a problem? Please describe.**
Currently, it's not possible to use a Stencil web component with template ref in Angular, which limits the flexibility of using Stencil components in Angular applications.

**Describe the solution you'd like**
I would like to request the feature of being able to use Stencil web components with template ref in Angular. Specifically, I want to be able to access the properties of the Stencil component using the template ref syntax in Angular templates.

For example, I have a Stencil component called "my-icon" with a property "iconName". I want to be able to use this component in an Angular template as follows:

```html
<my-icon #myIcon [iconName]="myIcon.myIconProperty.ANNOUNCEMENT"></my-icon>
```

Here, the "myIcon" template reference variable is used to access the "myIconProperty" property of the Stencil component and set the value of the "iconName" property.

**Describe alternatives you've considered**
Currently, there are no alternatives available to achieve this functionality.

**Additional context**
This feature will enhance the interoperability between Stencil and Angular, allowing developers to use Stencil components more easily in their Angular applications. It will also improve the developer experience and make it more intuitive and consistent with the Angular syntax.

**Comment by DominikPieper** [comment]
We just add the outputtargets plugin for angular. This feature request would be better there, we don't have anything to do with the generation itself.

**Comment by DominikPieper** [comment]
https://github.com/ionic-team/stencil-ds-output-targets
