### ISSUE TITLE
Ionic: What's going on.

### ISSUE THREAD

**Issue by NoMoreTickets** [nxext/nx-extensions#951]
General environment:

Macbook Pro, M1, nodejs lts (v18.16.0)

**Describe the bug**
 
I create 

**To Reproduce**

1. On mac, with node v18.16.0
2. Create a nx workspace

```
npx create-nx-workspace --preset=angular 
```

3. Choose "angular monorepo". 
4. Set repo name to "testws"
5. Set app name to "testwsapp"
6. Answer "Would you like to use Standalone Components in your application?" with "No"
7. Answer "Would you like to add routing?" with "Yes"
8. Select "SASS"
9. Select "No" for enable caching
10. cd to "testws" directory
11. Run command 
```
 npm install --save-dev --exact @nxext/ionic-angular
```

This generates the following error

<img width="645" alt="Screenshot 2023-05-22 at 2 36 21 PM" src="https://github.com/nxext/nx-extensions/assets/108766520/8fcea390-a80d-430f-8d87-0d54815f808c">

**Expected behavior**

I'd expect the library would be able to be installed or there would be more detailed info in documentation about what addition requirements there are or more warning messages logged in the terminal as to why what I was trying to do is unfeasible.

**Additional context**

It would help if the ionic documentation section had a "stem-to-stern" set of instructions that walks through creating the nx workspace, doing every depedency install necessary, etc. Too many steps documented is far better than too little. Abbreviating redundant steps is bad.

**Comment by nhhockeyplayer** [comment]
field is fuming... major corporations are asking for something real here and consultants cannot deliver.
https://github.com/nrwl/nx/issues/16696
ionic angular on capacitor for NX monorepo has been nailed broken since 2 yrs ago with nxtend and it remains broken within nxext now where it migrated to live https://github.com/nxext/nx-extensions/issues/950 

NRWL TEAM NOT DELIVERING

cant rollback migrations... what happens on a new PC if you install NX to find out everything running in the field is anchored to 12, 13, 14 lucky if its on 15 and NX 16 cannot do anything with it 

angular is getting the worst of it

**Comment by NoMoreTickets** [comment]
<soapbox>
When pressed, I tell people that the most reliable, most effective way to deliver a mobile app is by using a two-codebase solution with Swift on iOS and Kotlin on Android, because any savings you get from using one-codebase is quickly eaten up by the time and money costs of maintaining the glue of a massive, brittle, complicated hybrid mobile development stack with many moving parts that's subject to the whims and ebbs of the JS ecosystem.

And that's *before* you try to add it to a monorepo, at which point you're adding an even more brittle, customized dialect of the already brittle hybrid stack, one that's now designed to sit in a monorepo.
</soapbox>

But that being said, it would be helpful is @DominikPieper or someone would add something like a [Solidarity](https://github.com/infinitered/solidarity) that would prevent installation/running of nxext installation if the right combination of node/nx/etc isn't installed on the machine. And maybe put a bigger warning label about this in docs.

**Comment by nhhockeyplayer** [comment]
Nx 16 looking fab from my lens as of today for influencing these frameworks
